// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginaichatask

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AskPostResponseable instead.
type AskResponse struct {
    AskPostResponse
}
// NewAskResponse instantiates a new AskResponse and sets the default values.
func NewAskResponse()(*AskResponse) {
    m := &AskResponse{
        AskPostResponse: *NewAskPostResponse(),
    }
    return m
}
// CreateAskResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAskResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAskResponse(), nil
}
// Deprecated: This class is obsolete. Use AskPostResponseable instead.
type AskResponseable interface {
    AskPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
