// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginaichatask

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// PluginAichatAskRequestBuilder builds and executes requests for operations under \plugin.aichat.ask
type PluginAichatAskRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// PluginAichatAskRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type PluginAichatAskRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewPluginAichatAskRequestBuilderInternal instantiates a new PluginAichatAskRequestBuilder and sets the default values.
func NewPluginAichatAskRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginAichatAskRequestBuilder) {
    m := &PluginAichatAskRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/plugin.aichat.ask", pathParameters),
    }
    return m
}
// NewPluginAichatAskRequestBuilder instantiates a new PluginAichatAskRequestBuilder and sets the default values.
func NewPluginAichatAskRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginAichatAskRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewPluginAichatAskRequestBuilderInternal(urlParams, requestAdapter)
}
// Post sends the given question to the LLM and returns the answer, including the used sources.
// Deprecated: This method is obsolete. Use PostAsAskPostResponse instead.
// returns a AskResponseable when successful
func (m *PluginAichatAskRequestBuilder) Post(ctx context.Context, body AskPostRequestBodyable, requestConfiguration *PluginAichatAskRequestBuilderPostRequestConfiguration)(AskResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateAskResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(AskResponseable), nil
}
// PostAsAskPostResponse sends the given question to the LLM and returns the answer, including the used sources.
// returns a AskPostResponseable when successful
func (m *PluginAichatAskRequestBuilder) PostAsAskPostResponse(ctx context.Context, body AskPostRequestBodyable, requestConfiguration *PluginAichatAskRequestBuilderPostRequestConfiguration)(AskPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateAskPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(AskPostResponseable), nil
}
// ToPostRequestInformation sends the given question to the LLM and returns the answer, including the used sources.
// returns a *RequestInformation when successful
func (m *PluginAichatAskRequestBuilder) ToPostRequestInformation(ctx context.Context, body AskPostRequestBodyable, requestConfiguration *PluginAichatAskRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *PluginAichatAskRequestBuilder when successful
func (m *PluginAichatAskRequestBuilder) WithUrl(rawUrl string)(*PluginAichatAskRequestBuilder) {
    return NewPluginAichatAskRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
