// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dokuwikigettitle

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DokuwikiGetTitleRequestBuilder builds and executes requests for operations under \dokuwiki.getTitle
type DokuwikiGetTitleRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// DokuwikiGetTitleRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type DokuwikiGetTitleRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewDokuwikiGetTitleRequestBuilderInternal instantiates a new DokuwikiGetTitleRequestBuilder and sets the default values.
func NewDokuwikiGetTitleRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DokuwikiGetTitleRequestBuilder) {
    m := &DokuwikiGetTitleRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/dokuwiki.getTitle", pathParameters),
    }
    return m
}
// NewDokuwikiGetTitleRequestBuilder instantiates a new DokuwikiGetTitleRequestBuilder and sets the default values.
func NewDokuwikiGetTitleRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DokuwikiGetTitleRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewDokuwikiGetTitleRequestBuilderInternal(urlParams, requestAdapter)
}
// Post **This method is deprecated.** use core.getWikiTitle insteadThis method is public and does not require authentication. 
// Deprecated: This method is obsolete. Use PostAsGetTitlePostResponse instead.
// returns a GetTitleResponseable when successful
func (m *DokuwikiGetTitleRequestBuilder) Post(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *DokuwikiGetTitleRequestBuilderPostRequestConfiguration)(GetTitleResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetTitleResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetTitleResponseable), nil
}
// PostAsGetTitlePostResponse **This method is deprecated.** use core.getWikiTitle insteadThis method is public and does not require authentication. 
// Deprecated: 
// returns a GetTitlePostResponseable when successful
func (m *DokuwikiGetTitleRequestBuilder) PostAsGetTitlePostResponse(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *DokuwikiGetTitleRequestBuilderPostRequestConfiguration)(GetTitlePostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetTitlePostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetTitlePostResponseable), nil
}
// ToPostRequestInformation **This method is deprecated.** use core.getWikiTitle insteadThis method is public and does not require authentication. 
// Deprecated: 
// returns a *RequestInformation when successful
func (m *DokuwikiGetTitleRequestBuilder) ToPostRequestInformation(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *DokuwikiGetTitleRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    requestInfo.SetContentFromScalar(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// Deprecated: 
// returns a *DokuwikiGetTitleRequestBuilder when successful
func (m *DokuwikiGetTitleRequestBuilder) WithUrl(rawUrl string)(*DokuwikiGetTitleRequestBuilder) {
    return NewDokuwikiGetTitleRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
