// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package wikilistlinks

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ListLinksPostResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Error object in case of an error
    error ListLinksPostResponse_errorable
    // The result property
    result ListLinksPostResponse_resultable
}
// NewListLinksPostResponse instantiates a new ListLinksPostResponse and sets the default values.
func NewListLinksPostResponse()(*ListLinksPostResponse) {
    m := &ListLinksPostResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateListLinksPostResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateListLinksPostResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewListLinksPostResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ListLinksPostResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetError gets the error property value. Error object in case of an error
// returns a ListLinksPostResponse_errorable when successful
func (m *ListLinksPostResponse) GetError()(ListLinksPostResponse_errorable) {
    return m.error
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ListLinksPostResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["error"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateListLinksPostResponse_errorFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetError(val.(ListLinksPostResponse_errorable))
        }
        return nil
    }
    res["result"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateListLinksPostResponse_resultFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResult(val.(ListLinksPostResponse_resultable))
        }
        return nil
    }
    return res
}
// GetResult gets the result property value. The result property
// returns a ListLinksPostResponse_resultable when successful
func (m *ListLinksPostResponse) GetResult()(ListLinksPostResponse_resultable) {
    return m.result
}
// Serialize serializes information the current object
func (m *ListLinksPostResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("error", m.GetError())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("result", m.GetResult())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ListLinksPostResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetError sets the error property value. Error object in case of an error
func (m *ListLinksPostResponse) SetError(value ListLinksPostResponse_errorable)() {
    m.error = value
}
// SetResult sets the result property value. The result property
func (m *ListLinksPostResponse) SetResult(value ListLinksPostResponse_resultable)() {
    m.result = value
}
type ListLinksPostResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetError()(ListLinksPostResponse_errorable)
    GetResult()(ListLinksPostResponse_resultable)
    SetError(value ListLinksPostResponse_errorable)()
    SetResult(value ListLinksPostResponse_resultable)()
}
