// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coregetpagehistory

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetPageHistoryPostResponseable instead.
type GetPageHistoryResponse struct {
    GetPageHistoryPostResponse
}
// NewGetPageHistoryResponse instantiates a new GetPageHistoryResponse and sets the default values.
func NewGetPageHistoryResponse()(*GetPageHistoryResponse) {
    m := &GetPageHistoryResponse{
        GetPageHistoryPostResponse: *NewGetPageHistoryPostResponse(),
    }
    return m
}
// CreateGetPageHistoryResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetPageHistoryResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetPageHistoryResponse(), nil
}
// Deprecated: This class is obsolete. Use GetPageHistoryPostResponseable instead.
type GetPageHistoryResponseable interface {
    GetPageHistoryPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
