// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coregetpagehistory

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GetPageHistoryPostResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Error object in case of an error
    error GetPageHistoryPostResponse_errorable
    // The result property
    result []GetPageHistoryPostResponse_resultable
}
// NewGetPageHistoryPostResponse instantiates a new GetPageHistoryPostResponse and sets the default values.
func NewGetPageHistoryPostResponse()(*GetPageHistoryPostResponse) {
    m := &GetPageHistoryPostResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGetPageHistoryPostResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetPageHistoryPostResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetPageHistoryPostResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GetPageHistoryPostResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetError gets the error property value. Error object in case of an error
// returns a GetPageHistoryPostResponse_errorable when successful
func (m *GetPageHistoryPostResponse) GetError()(GetPageHistoryPostResponse_errorable) {
    return m.error
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GetPageHistoryPostResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["error"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateGetPageHistoryPostResponse_errorFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetError(val.(GetPageHistoryPostResponse_errorable))
        }
        return nil
    }
    res["result"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateGetPageHistoryPostResponse_resultFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]GetPageHistoryPostResponse_resultable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(GetPageHistoryPostResponse_resultable)
                }
            }
            m.SetResult(res)
        }
        return nil
    }
    return res
}
// GetResult gets the result property value. The result property
// returns a []GetPageHistoryPostResponse_resultable when successful
func (m *GetPageHistoryPostResponse) GetResult()([]GetPageHistoryPostResponse_resultable) {
    return m.result
}
// Serialize serializes information the current object
func (m *GetPageHistoryPostResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("error", m.GetError())
        if err != nil {
            return err
        }
    }
    if m.GetResult() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetResult()))
        for i, v := range m.GetResult() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("result", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GetPageHistoryPostResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetError sets the error property value. Error object in case of an error
func (m *GetPageHistoryPostResponse) SetError(value GetPageHistoryPostResponse_errorable)() {
    m.error = value
}
// SetResult sets the result property value. The result property
func (m *GetPageHistoryPostResponse) SetResult(value []GetPageHistoryPostResponse_resultable)() {
    m.result = value
}
type GetPageHistoryPostResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetError()(GetPageHistoryPostResponse_errorable)
    GetResult()([]GetPageHistoryPostResponse_resultable)
    SetError(value GetPageHistoryPostResponse_errorable)()
    SetResult(value []GetPageHistoryPostResponse_resultable)()
}
