// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coregetpageinfo

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GetPageInfoPostRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // whether to include the author information [_default: `false`_]
    author *bool
    // whether to include the MD5 hash of the page content [_default: `false`_]
    hash *bool
    // page id
    page *string
    // revision timestamp [_default: `0`_]
    rev *int32
}
// NewGetPageInfoPostRequestBody instantiates a new GetPageInfoPostRequestBody and sets the default values.
func NewGetPageInfoPostRequestBody()(*GetPageInfoPostRequestBody) {
    m := &GetPageInfoPostRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGetPageInfoPostRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetPageInfoPostRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetPageInfoPostRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GetPageInfoPostRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAuthor gets the author property value. whether to include the author information [_default: `false`_]
// returns a *bool when successful
func (m *GetPageInfoPostRequestBody) GetAuthor()(*bool) {
    return m.author
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GetPageInfoPostRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["author"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAuthor(val)
        }
        return nil
    }
    res["hash"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHash(val)
        }
        return nil
    }
    res["page"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPage(val)
        }
        return nil
    }
    res["rev"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRev(val)
        }
        return nil
    }
    return res
}
// GetHash gets the hash property value. whether to include the MD5 hash of the page content [_default: `false`_]
// returns a *bool when successful
func (m *GetPageInfoPostRequestBody) GetHash()(*bool) {
    return m.hash
}
// GetPage gets the page property value. page id
// returns a *string when successful
func (m *GetPageInfoPostRequestBody) GetPage()(*string) {
    return m.page
}
// GetRev gets the rev property value. revision timestamp [_default: `0`_]
// returns a *int32 when successful
func (m *GetPageInfoPostRequestBody) GetRev()(*int32) {
    return m.rev
}
// Serialize serializes information the current object
func (m *GetPageInfoPostRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("author", m.GetAuthor())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("hash", m.GetHash())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("page", m.GetPage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("rev", m.GetRev())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GetPageInfoPostRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAuthor sets the author property value. whether to include the author information [_default: `false`_]
func (m *GetPageInfoPostRequestBody) SetAuthor(value *bool)() {
    m.author = value
}
// SetHash sets the hash property value. whether to include the MD5 hash of the page content [_default: `false`_]
func (m *GetPageInfoPostRequestBody) SetHash(value *bool)() {
    m.hash = value
}
// SetPage sets the page property value. page id
func (m *GetPageInfoPostRequestBody) SetPage(value *string)() {
    m.page = value
}
// SetRev sets the rev property value. revision timestamp [_default: `0`_]
func (m *GetPageInfoPostRequestBody) SetRev(value *int32)() {
    m.rev = value
}
type GetPageInfoPostRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAuthor()(*bool)
    GetHash()(*bool)
    GetPage()(*string)
    GetRev()(*int32)
    SetAuthor(value *bool)()
    SetHash(value *bool)()
    SetPage(value *string)()
    SetRev(value *int32)()
}
