// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coredeletemedia

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CoreDeleteMediaRequestBuilder builds and executes requests for operations under \core.deleteMedia
type CoreDeleteMediaRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CoreDeleteMediaRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CoreDeleteMediaRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewCoreDeleteMediaRequestBuilderInternal instantiates a new CoreDeleteMediaRequestBuilder and sets the default values.
func NewCoreDeleteMediaRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreDeleteMediaRequestBuilder) {
    m := &CoreDeleteMediaRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/core.deleteMedia", pathParameters),
    }
    return m
}
// NewCoreDeleteMediaRequestBuilder instantiates a new CoreDeleteMediaRequestBuilder and sets the default values.
func NewCoreDeleteMediaRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreDeleteMediaRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCoreDeleteMediaRequestBuilderInternal(urlParams, requestAdapter)
}
// Post you need to have delete permissions for the file.
// Deprecated: This method is obsolete. Use PostAsDeleteMediaPostResponse instead.
// returns a DeleteMediaResponseable when successful
func (m *CoreDeleteMediaRequestBuilder) Post(ctx context.Context, body DeleteMediaPostRequestBodyable, requestConfiguration *CoreDeleteMediaRequestBuilderPostRequestConfiguration)(DeleteMediaResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateDeleteMediaResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(DeleteMediaResponseable), nil
}
// PostAsDeleteMediaPostResponse you need to have delete permissions for the file.
// returns a DeleteMediaPostResponseable when successful
func (m *CoreDeleteMediaRequestBuilder) PostAsDeleteMediaPostResponse(ctx context.Context, body DeleteMediaPostRequestBodyable, requestConfiguration *CoreDeleteMediaRequestBuilderPostRequestConfiguration)(DeleteMediaPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateDeleteMediaPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(DeleteMediaPostResponseable), nil
}
// ToPostRequestInformation you need to have delete permissions for the file.
// returns a *RequestInformation when successful
func (m *CoreDeleteMediaRequestBuilder) ToPostRequestInformation(ctx context.Context, body DeleteMediaPostRequestBodyable, requestConfiguration *CoreDeleteMediaRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CoreDeleteMediaRequestBuilder when successful
func (m *CoreDeleteMediaRequestBuilder) WithUrl(rawUrl string)(*CoreDeleteMediaRequestBuilder) {
    return NewCoreDeleteMediaRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
