// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginextensioninstall

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// PluginExtensionInstallRequestBuilder builds and executes requests for operations under \plugin.extension.install
type PluginExtensionInstallRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// PluginExtensionInstallRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type PluginExtensionInstallRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewPluginExtensionInstallRequestBuilderInternal instantiates a new PluginExtensionInstallRequestBuilder and sets the default values.
func NewPluginExtensionInstallRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginExtensionInstallRequestBuilder) {
    m := &PluginExtensionInstallRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/plugin.extension.install", pathParameters),
    }
    return m
}
// NewPluginExtensionInstallRequestBuilder instantiates a new PluginExtensionInstallRequestBuilder and sets the default values.
func NewPluginExtensionInstallRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginExtensionInstallRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewPluginExtensionInstallRequestBuilderInternal(urlParams, requestAdapter)
}
// Post this will also install dependencies, so more than the given extension may be installed.
// Deprecated: This method is obsolete. Use PostAsInstallPostResponse instead.
// returns a InstallResponseable when successful
func (m *PluginExtensionInstallRequestBuilder) Post(ctx context.Context, body InstallPostRequestBodyable, requestConfiguration *PluginExtensionInstallRequestBuilderPostRequestConfiguration)(InstallResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateInstallResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(InstallResponseable), nil
}
// PostAsInstallPostResponse this will also install dependencies, so more than the given extension may be installed.
// returns a InstallPostResponseable when successful
func (m *PluginExtensionInstallRequestBuilder) PostAsInstallPostResponse(ctx context.Context, body InstallPostRequestBodyable, requestConfiguration *PluginExtensionInstallRequestBuilderPostRequestConfiguration)(InstallPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateInstallPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(InstallPostResponseable), nil
}
// ToPostRequestInformation this will also install dependencies, so more than the given extension may be installed.
// returns a *RequestInformation when successful
func (m *PluginExtensionInstallRequestBuilder) ToPostRequestInformation(ctx context.Context, body InstallPostRequestBodyable, requestConfiguration *PluginExtensionInstallRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *PluginExtensionInstallRequestBuilder when successful
func (m *PluginExtensionInstallRequestBuilder) WithUrl(rawUrl string)(*PluginExtensionInstallRequestBuilder) {
    return NewPluginExtensionInstallRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
