// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginusermanagercreateuser

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// PluginUsermanagerCreateUserRequestBuilder builds and executes requests for operations under \plugin.usermanager.createUser
type PluginUsermanagerCreateUserRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// PluginUsermanagerCreateUserRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type PluginUsermanagerCreateUserRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewPluginUsermanagerCreateUserRequestBuilderInternal instantiates a new PluginUsermanagerCreateUserRequestBuilder and sets the default values.
func NewPluginUsermanagerCreateUserRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginUsermanagerCreateUserRequestBuilder) {
    m := &PluginUsermanagerCreateUserRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/plugin.usermanager.createUser", pathParameters),
    }
    return m
}
// NewPluginUsermanagerCreateUserRequestBuilder instantiates a new PluginUsermanagerCreateUserRequestBuilder and sets the default values.
func NewPluginUsermanagerCreateUserRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginUsermanagerCreateUserRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewPluginUsermanagerCreateUserRequestBuilderInternal(urlParams, requestAdapter)
}
// Post if no password is provided, a password is auto generated. If the user can't be createdby the auth backend a return value of `false` is returned. You need to check this returnvalue rather than relying on the error code only.Superuser permission are required to create users.
// Deprecated: This method is obsolete. Use PostAsCreateUserPostResponse instead.
// returns a CreateUserResponseable when successful
func (m *PluginUsermanagerCreateUserRequestBuilder) Post(ctx context.Context, body CreateUserPostRequestBodyable, requestConfiguration *PluginUsermanagerCreateUserRequestBuilderPostRequestConfiguration)(CreateUserResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateCreateUserResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(CreateUserResponseable), nil
}
// PostAsCreateUserPostResponse if no password is provided, a password is auto generated. If the user can't be createdby the auth backend a return value of `false` is returned. You need to check this returnvalue rather than relying on the error code only.Superuser permission are required to create users.
// returns a CreateUserPostResponseable when successful
func (m *PluginUsermanagerCreateUserRequestBuilder) PostAsCreateUserPostResponse(ctx context.Context, body CreateUserPostRequestBodyable, requestConfiguration *PluginUsermanagerCreateUserRequestBuilderPostRequestConfiguration)(CreateUserPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateCreateUserPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(CreateUserPostResponseable), nil
}
// ToPostRequestInformation if no password is provided, a password is auto generated. If the user can't be createdby the auth backend a return value of `false` is returned. You need to check this returnvalue rather than relying on the error code only.Superuser permission are required to create users.
// returns a *RequestInformation when successful
func (m *PluginUsermanagerCreateUserRequestBuilder) ToPostRequestInformation(ctx context.Context, body CreateUserPostRequestBodyable, requestConfiguration *PluginUsermanagerCreateUserRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *PluginUsermanagerCreateUserRequestBuilder when successful
func (m *PluginUsermanagerCreateUserRequestBuilder) WithUrl(rawUrl string)(*PluginUsermanagerCreateUserRequestBuilder) {
    return NewPluginUsermanagerCreateUserRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
