// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dokuwikigetversion

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DokuwikiGetVersionRequestBuilder builds and executes requests for operations under \dokuwiki.getVersion
type DokuwikiGetVersionRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// DokuwikiGetVersionRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type DokuwikiGetVersionRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewDokuwikiGetVersionRequestBuilderInternal instantiates a new DokuwikiGetVersionRequestBuilder and sets the default values.
func NewDokuwikiGetVersionRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DokuwikiGetVersionRequestBuilder) {
    m := &DokuwikiGetVersionRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/dokuwiki.getVersion", pathParameters),
    }
    return m
}
// NewDokuwikiGetVersionRequestBuilder instantiates a new DokuwikiGetVersionRequestBuilder and sets the default values.
func NewDokuwikiGetVersionRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DokuwikiGetVersionRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewDokuwikiGetVersionRequestBuilderInternal(urlParams, requestAdapter)
}
// Post **This method is deprecated.** use core.getWikiVersion instead
// Deprecated: This method is obsolete. Use PostAsGetVersionPostResponse instead.
// returns a GetVersionResponseable when successful
func (m *DokuwikiGetVersionRequestBuilder) Post(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *DokuwikiGetVersionRequestBuilderPostRequestConfiguration)(GetVersionResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetVersionResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetVersionResponseable), nil
}
// PostAsGetVersionPostResponse **This method is deprecated.** use core.getWikiVersion instead
// Deprecated: 
// returns a GetVersionPostResponseable when successful
func (m *DokuwikiGetVersionRequestBuilder) PostAsGetVersionPostResponse(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *DokuwikiGetVersionRequestBuilderPostRequestConfiguration)(GetVersionPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetVersionPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetVersionPostResponseable), nil
}
// ToPostRequestInformation **This method is deprecated.** use core.getWikiVersion instead
// Deprecated: 
// returns a *RequestInformation when successful
func (m *DokuwikiGetVersionRequestBuilder) ToPostRequestInformation(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *DokuwikiGetVersionRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    requestInfo.SetContentFromScalar(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// Deprecated: 
// returns a *DokuwikiGetVersionRequestBuilder when successful
func (m *DokuwikiGetVersionRequestBuilder) WithUrl(rawUrl string)(*DokuwikiGetVersionRequestBuilder) {
    return NewDokuwikiGetVersionRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
