// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dokuwikigetversion

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetVersionPostResponseable instead.
type GetVersionResponse struct {
    GetVersionPostResponse
}
// NewGetVersionResponse instantiates a new GetVersionResponse and sets the default values.
func NewGetVersionResponse()(*GetVersionResponse) {
    m := &GetVersionResponse{
        GetVersionPostResponse: *NewGetVersionPostResponse(),
    }
    return m
}
// CreateGetVersionResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetVersionResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetVersionResponse(), nil
}
// Deprecated: This class is obsolete. Use GetVersionPostResponseable instead.
type GetVersionResponseable interface {
    GetVersionPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
