// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dokuwikideleteusers

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DeleteUsersPostResponseable instead.
type DeleteUsersResponse struct {
    DeleteUsersPostResponse
}
// NewDeleteUsersResponse instantiates a new DeleteUsersResponse and sets the default values.
func NewDeleteUsersResponse()(*DeleteUsersResponse) {
    m := &DeleteUsersResponse{
        DeleteUsersPostResponse: *NewDeleteUsersPostResponse(),
    }
    return m
}
// CreateDeleteUsersResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeleteUsersResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDeleteUsersResponse(), nil
}
// Deprecated: This class is obsolete. Use DeleteUsersPostResponseable instead.
type DeleteUsersResponseable interface {
    DeleteUsersPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
