// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dokuwikideleteusers

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// DokuwikiDeleteUsersRequestBuilder builds and executes requests for operations under \dokuwiki.deleteUsers
type DokuwikiDeleteUsersRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// DokuwikiDeleteUsersRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type DokuwikiDeleteUsersRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewDokuwikiDeleteUsersRequestBuilderInternal instantiates a new DokuwikiDeleteUsersRequestBuilder and sets the default values.
func NewDokuwikiDeleteUsersRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DokuwikiDeleteUsersRequestBuilder) {
    m := &DokuwikiDeleteUsersRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/dokuwiki.deleteUsers", pathParameters),
    }
    return m
}
// NewDokuwikiDeleteUsersRequestBuilder instantiates a new DokuwikiDeleteUsersRequestBuilder and sets the default values.
func NewDokuwikiDeleteUsersRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DokuwikiDeleteUsersRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewDokuwikiDeleteUsersRequestBuilderInternal(urlParams, requestAdapter)
}
// Post **This method is deprecated.** use plugin.usermanager.deleteUser instead
// Deprecated: This method is obsolete. Use PostAsDeleteUsersPostResponse instead.
// returns a DeleteUsersResponseable when successful
func (m *DokuwikiDeleteUsersRequestBuilder) Post(ctx context.Context, body DeleteUsersPostRequestBodyable, requestConfiguration *DokuwikiDeleteUsersRequestBuilderPostRequestConfiguration)(DeleteUsersResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateDeleteUsersResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(DeleteUsersResponseable), nil
}
// PostAsDeleteUsersPostResponse **This method is deprecated.** use plugin.usermanager.deleteUser instead
// Deprecated: 
// returns a DeleteUsersPostResponseable when successful
func (m *DokuwikiDeleteUsersRequestBuilder) PostAsDeleteUsersPostResponse(ctx context.Context, body DeleteUsersPostRequestBodyable, requestConfiguration *DokuwikiDeleteUsersRequestBuilderPostRequestConfiguration)(DeleteUsersPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateDeleteUsersPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(DeleteUsersPostResponseable), nil
}
// ToPostRequestInformation **This method is deprecated.** use plugin.usermanager.deleteUser instead
// Deprecated: 
// returns a *RequestInformation when successful
func (m *DokuwikiDeleteUsersRequestBuilder) ToPostRequestInformation(ctx context.Context, body DeleteUsersPostRequestBodyable, requestConfiguration *DokuwikiDeleteUsersRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// Deprecated: 
// returns a *DokuwikiDeleteUsersRequestBuilder when successful
func (m *DokuwikiDeleteUsersRequestBuilder) WithUrl(rawUrl string)(*DokuwikiDeleteUsersRequestBuilder) {
    return NewDokuwikiDeleteUsersRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
