// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginacladdacl

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use AddAclPostResponseable instead.
type AddAclResponse struct {
    AddAclPostResponse
}
// NewAddAclResponse instantiates a new AddAclResponse and sets the default values.
func NewAddAclResponse()(*AddAclResponse) {
    m := &AddAclResponse{
        AddAclPostResponse: *NewAddAclPostResponse(),
    }
    return m
}
// CreateAddAclResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAddAclResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAddAclResponse(), nil
}
// Deprecated: This class is obsolete. Use AddAclPostResponseable instead.
type AddAclResponseable interface {
    AddAclPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
