// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginacldelacl

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use DelAclPostResponseable instead.
type DelAclResponse struct {
    DelAclPostResponse
}
// NewDelAclResponse instantiates a new DelAclResponse and sets the default values.
func NewDelAclResponse()(*DelAclResponse) {
    m := &DelAclResponse{
        DelAclPostResponse: *NewDelAclPostResponse(),
    }
    return m
}
// CreateDelAclResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDelAclResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDelAclResponse(), nil
}
// Deprecated: This class is obsolete. Use DelAclPostResponseable instead.
type DelAclResponseable interface {
    DelAclPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
