// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coregetmediainfo

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GetMediaInfoPostResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Error object in case of an error
    error GetMediaInfoPostResponse_errorable
    // The result property
    result GetMediaInfoPostResponse_resultable
}
// NewGetMediaInfoPostResponse instantiates a new GetMediaInfoPostResponse and sets the default values.
func NewGetMediaInfoPostResponse()(*GetMediaInfoPostResponse) {
    m := &GetMediaInfoPostResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGetMediaInfoPostResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetMediaInfoPostResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetMediaInfoPostResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GetMediaInfoPostResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetError gets the error property value. Error object in case of an error
// returns a GetMediaInfoPostResponse_errorable when successful
func (m *GetMediaInfoPostResponse) GetError()(GetMediaInfoPostResponse_errorable) {
    return m.error
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GetMediaInfoPostResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["error"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateGetMediaInfoPostResponse_errorFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetError(val.(GetMediaInfoPostResponse_errorable))
        }
        return nil
    }
    res["result"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateGetMediaInfoPostResponse_resultFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResult(val.(GetMediaInfoPostResponse_resultable))
        }
        return nil
    }
    return res
}
// GetResult gets the result property value. The result property
// returns a GetMediaInfoPostResponse_resultable when successful
func (m *GetMediaInfoPostResponse) GetResult()(GetMediaInfoPostResponse_resultable) {
    return m.result
}
// Serialize serializes information the current object
func (m *GetMediaInfoPostResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("error", m.GetError())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("result", m.GetResult())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GetMediaInfoPostResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetError sets the error property value. Error object in case of an error
func (m *GetMediaInfoPostResponse) SetError(value GetMediaInfoPostResponse_errorable)() {
    m.error = value
}
// SetResult sets the result property value. The result property
func (m *GetMediaInfoPostResponse) SetResult(value GetMediaInfoPostResponse_resultable)() {
    m.result = value
}
type GetMediaInfoPostResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetError()(GetMediaInfoPostResponse_errorable)
    GetResult()(GetMediaInfoPostResponse_resultable)
    SetError(value GetMediaInfoPostResponse_errorable)()
    SetResult(value GetMediaInfoPostResponse_resultable)()
}
