// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coregetmediainfo

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GetMediaInfoPostRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // whether to include the author information [_default: `false`_]
    author *bool
    // whether to include the MD5 hash of the media content [_default: `false`_]
    hash *bool
    // file id
    media *string
    // revision timestamp [_default: `0`_]
    rev *int32
}
// NewGetMediaInfoPostRequestBody instantiates a new GetMediaInfoPostRequestBody and sets the default values.
func NewGetMediaInfoPostRequestBody()(*GetMediaInfoPostRequestBody) {
    m := &GetMediaInfoPostRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGetMediaInfoPostRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetMediaInfoPostRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetMediaInfoPostRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GetMediaInfoPostRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAuthor gets the author property value. whether to include the author information [_default: `false`_]
// returns a *bool when successful
func (m *GetMediaInfoPostRequestBody) GetAuthor()(*bool) {
    return m.author
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GetMediaInfoPostRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["author"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAuthor(val)
        }
        return nil
    }
    res["hash"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHash(val)
        }
        return nil
    }
    res["media"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMedia(val)
        }
        return nil
    }
    res["rev"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRev(val)
        }
        return nil
    }
    return res
}
// GetHash gets the hash property value. whether to include the MD5 hash of the media content [_default: `false`_]
// returns a *bool when successful
func (m *GetMediaInfoPostRequestBody) GetHash()(*bool) {
    return m.hash
}
// GetMedia gets the media property value. file id
// returns a *string when successful
func (m *GetMediaInfoPostRequestBody) GetMedia()(*string) {
    return m.media
}
// GetRev gets the rev property value. revision timestamp [_default: `0`_]
// returns a *int32 when successful
func (m *GetMediaInfoPostRequestBody) GetRev()(*int32) {
    return m.rev
}
// Serialize serializes information the current object
func (m *GetMediaInfoPostRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("author", m.GetAuthor())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("hash", m.GetHash())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("media", m.GetMedia())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("rev", m.GetRev())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GetMediaInfoPostRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAuthor sets the author property value. whether to include the author information [_default: `false`_]
func (m *GetMediaInfoPostRequestBody) SetAuthor(value *bool)() {
    m.author = value
}
// SetHash sets the hash property value. whether to include the MD5 hash of the media content [_default: `false`_]
func (m *GetMediaInfoPostRequestBody) SetHash(value *bool)() {
    m.hash = value
}
// SetMedia sets the media property value. file id
func (m *GetMediaInfoPostRequestBody) SetMedia(value *string)() {
    m.media = value
}
// SetRev sets the rev property value. revision timestamp [_default: `0`_]
func (m *GetMediaInfoPostRequestBody) SetRev(value *int32)() {
    m.rev = value
}
type GetMediaInfoPostRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAuthor()(*bool)
    GetHash()(*bool)
    GetMedia()(*string)
    GetRev()(*int32)
    SetAuthor(value *bool)()
    SetHash(value *bool)()
    SetMedia(value *string)()
    SetRev(value *int32)()
}
