// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package wikigetrecentmediachanges

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GetRecentMediaChangesPostResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Error object in case of an error
    error GetRecentMediaChangesPostResponse_errorable
    // The result property
    result GetRecentMediaChangesPostResponse_resultable
}
// NewGetRecentMediaChangesPostResponse instantiates a new GetRecentMediaChangesPostResponse and sets the default values.
func NewGetRecentMediaChangesPostResponse()(*GetRecentMediaChangesPostResponse) {
    m := &GetRecentMediaChangesPostResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGetRecentMediaChangesPostResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetRecentMediaChangesPostResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetRecentMediaChangesPostResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GetRecentMediaChangesPostResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetError gets the error property value. Error object in case of an error
// returns a GetRecentMediaChangesPostResponse_errorable when successful
func (m *GetRecentMediaChangesPostResponse) GetError()(GetRecentMediaChangesPostResponse_errorable) {
    return m.error
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GetRecentMediaChangesPostResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["error"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateGetRecentMediaChangesPostResponse_errorFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetError(val.(GetRecentMediaChangesPostResponse_errorable))
        }
        return nil
    }
    res["result"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateGetRecentMediaChangesPostResponse_resultFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResult(val.(GetRecentMediaChangesPostResponse_resultable))
        }
        return nil
    }
    return res
}
// GetResult gets the result property value. The result property
// returns a GetRecentMediaChangesPostResponse_resultable when successful
func (m *GetRecentMediaChangesPostResponse) GetResult()(GetRecentMediaChangesPostResponse_resultable) {
    return m.result
}
// Serialize serializes information the current object
func (m *GetRecentMediaChangesPostResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("error", m.GetError())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("result", m.GetResult())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GetRecentMediaChangesPostResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetError sets the error property value. Error object in case of an error
func (m *GetRecentMediaChangesPostResponse) SetError(value GetRecentMediaChangesPostResponse_errorable)() {
    m.error = value
}
// SetResult sets the result property value. The result property
func (m *GetRecentMediaChangesPostResponse) SetResult(value GetRecentMediaChangesPostResponse_resultable)() {
    m.result = value
}
type GetRecentMediaChangesPostResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetError()(GetRecentMediaChangesPostResponse_errorable)
    GetResult()(GetRecentMediaChangesPostResponse_resultable)
    SetError(value GetRecentMediaChangesPostResponse_errorable)()
    SetResult(value GetRecentMediaChangesPostResponse_resultable)()
}
