// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package wikigetattachments

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GetAttachmentsPostRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The ns property
    ns *string
    //  [_default: `[]`_]
    options *string
}
// NewGetAttachmentsPostRequestBody instantiates a new GetAttachmentsPostRequestBody and sets the default values.
func NewGetAttachmentsPostRequestBody()(*GetAttachmentsPostRequestBody) {
    m := &GetAttachmentsPostRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGetAttachmentsPostRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetAttachmentsPostRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetAttachmentsPostRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GetAttachmentsPostRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GetAttachmentsPostRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["ns"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNs(val)
        }
        return nil
    }
    res["options"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOptions(val)
        }
        return nil
    }
    return res
}
// GetNs gets the ns property value. The ns property
// returns a *string when successful
func (m *GetAttachmentsPostRequestBody) GetNs()(*string) {
    return m.ns
}
// GetOptions gets the options property value.  [_default: `[]`_]
// returns a *string when successful
func (m *GetAttachmentsPostRequestBody) GetOptions()(*string) {
    return m.options
}
// Serialize serializes information the current object
func (m *GetAttachmentsPostRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("ns", m.GetNs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("options", m.GetOptions())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GetAttachmentsPostRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetNs sets the ns property value. The ns property
func (m *GetAttachmentsPostRequestBody) SetNs(value *string)() {
    m.ns = value
}
// SetOptions sets the options property value.  [_default: `[]`_]
func (m *GetAttachmentsPostRequestBody) SetOptions(value *string)() {
    m.options = value
}
type GetAttachmentsPostRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetNs()(*string)
    GetOptions()(*string)
    SetNs(value *string)()
    SetOptions(value *string)()
}
