// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dokuwikigetxmlrpcapiversion

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DokuwikiGetXMLRPCAPIVersionRequestBuilder builds and executes requests for operations under \dokuwiki.getXMLRPCAPIVersion
type DokuwikiGetXMLRPCAPIVersionRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// DokuwikiGetXMLRPCAPIVersionRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type DokuwikiGetXMLRPCAPIVersionRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewDokuwikiGetXMLRPCAPIVersionRequestBuilderInternal instantiates a new DokuwikiGetXMLRPCAPIVersionRequestBuilder and sets the default values.
func NewDokuwikiGetXMLRPCAPIVersionRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DokuwikiGetXMLRPCAPIVersionRequestBuilder) {
    m := &DokuwikiGetXMLRPCAPIVersionRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/dokuwiki.getXMLRPCAPIVersion", pathParameters),
    }
    return m
}
// NewDokuwikiGetXMLRPCAPIVersionRequestBuilder instantiates a new DokuwikiGetXMLRPCAPIVersionRequestBuilder and sets the default values.
func NewDokuwikiGetXMLRPCAPIVersionRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*DokuwikiGetXMLRPCAPIVersionRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewDokuwikiGetXMLRPCAPIVersionRequestBuilderInternal(urlParams, requestAdapter)
}
// Post **This method is deprecated.** use core.getAPIVersion insteadThis method is public and does not require authentication. 
// Deprecated: This method is obsolete. Use PostAsGetXMLRPCAPIVersionPostResponse instead.
// returns a GetXMLRPCAPIVersionResponseable when successful
func (m *DokuwikiGetXMLRPCAPIVersionRequestBuilder) Post(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *DokuwikiGetXMLRPCAPIVersionRequestBuilderPostRequestConfiguration)(GetXMLRPCAPIVersionResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetXMLRPCAPIVersionResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetXMLRPCAPIVersionResponseable), nil
}
// PostAsGetXMLRPCAPIVersionPostResponse **This method is deprecated.** use core.getAPIVersion insteadThis method is public and does not require authentication. 
// Deprecated: 
// returns a GetXMLRPCAPIVersionPostResponseable when successful
func (m *DokuwikiGetXMLRPCAPIVersionRequestBuilder) PostAsGetXMLRPCAPIVersionPostResponse(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *DokuwikiGetXMLRPCAPIVersionRequestBuilderPostRequestConfiguration)(GetXMLRPCAPIVersionPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetXMLRPCAPIVersionPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetXMLRPCAPIVersionPostResponseable), nil
}
// ToPostRequestInformation **This method is deprecated.** use core.getAPIVersion insteadThis method is public and does not require authentication. 
// Deprecated: 
// returns a *RequestInformation when successful
func (m *DokuwikiGetXMLRPCAPIVersionRequestBuilder) ToPostRequestInformation(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *DokuwikiGetXMLRPCAPIVersionRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    requestInfo.SetContentFromScalar(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// Deprecated: 
// returns a *DokuwikiGetXMLRPCAPIVersionRequestBuilder when successful
func (m *DokuwikiGetXMLRPCAPIVersionRequestBuilder) WithUrl(rawUrl string)(*DokuwikiGetXMLRPCAPIVersionRequestBuilder) {
    return NewDokuwikiGetXMLRPCAPIVersionRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
