// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dokuwikigetxmlrpcapiversion

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetXMLRPCAPIVersionPostResponseable instead.
type GetXMLRPCAPIVersionResponse struct {
    GetXMLRPCAPIVersionPostResponse
}
// NewGetXMLRPCAPIVersionResponse instantiates a new GetXMLRPCAPIVersionResponse and sets the default values.
func NewGetXMLRPCAPIVersionResponse()(*GetXMLRPCAPIVersionResponse) {
    m := &GetXMLRPCAPIVersionResponse{
        GetXMLRPCAPIVersionPostResponse: *NewGetXMLRPCAPIVersionPostResponse(),
    }
    return m
}
// CreateGetXMLRPCAPIVersionResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetXMLRPCAPIVersionResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetXMLRPCAPIVersionResponse(), nil
}
// Deprecated: This class is obsolete. Use GetXMLRPCAPIVersionPostResponseable instead.
type GetXMLRPCAPIVersionResponseable interface {
    GetXMLRPCAPIVersionPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
