// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coresavepage

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CoreSavePageRequestBuilder builds and executes requests for operations under \core.savePage
type CoreSavePageRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CoreSavePageRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CoreSavePageRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewCoreSavePageRequestBuilderInternal instantiates a new CoreSavePageRequestBuilder and sets the default values.
func NewCoreSavePageRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreSavePageRequestBuilder) {
    m := &CoreSavePageRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/core.savePage", pathParameters),
    }
    return m
}
// NewCoreSavePageRequestBuilder instantiates a new CoreSavePageRequestBuilder and sets the default values.
func NewCoreSavePageRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreSavePageRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCoreSavePageRequestBuilderInternal(urlParams, requestAdapter)
}
// Post saves the given wiki text to the given page. If the page does not exist, it will be created.Just like in the wiki, saving an empty text will delete the page.You need write permissions for the given page and the page may not be locked by another user.
// Deprecated: This method is obsolete. Use PostAsSavePagePostResponse instead.
// returns a SavePageResponseable when successful
func (m *CoreSavePageRequestBuilder) Post(ctx context.Context, body SavePagePostRequestBodyable, requestConfiguration *CoreSavePageRequestBuilderPostRequestConfiguration)(SavePageResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateSavePageResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(SavePageResponseable), nil
}
// PostAsSavePagePostResponse saves the given wiki text to the given page. If the page does not exist, it will be created.Just like in the wiki, saving an empty text will delete the page.You need write permissions for the given page and the page may not be locked by another user.
// returns a SavePagePostResponseable when successful
func (m *CoreSavePageRequestBuilder) PostAsSavePagePostResponse(ctx context.Context, body SavePagePostRequestBodyable, requestConfiguration *CoreSavePageRequestBuilderPostRequestConfiguration)(SavePagePostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateSavePagePostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(SavePagePostResponseable), nil
}
// ToPostRequestInformation saves the given wiki text to the given page. If the page does not exist, it will be created.Just like in the wiki, saving an empty text will delete the page.You need write permissions for the given page and the page may not be locked by another user.
// returns a *RequestInformation when successful
func (m *CoreSavePageRequestBuilder) ToPostRequestInformation(ctx context.Context, body SavePagePostRequestBodyable, requestConfiguration *CoreSavePageRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CoreSavePageRequestBuilder when successful
func (m *CoreSavePageRequestBuilder) WithUrl(rawUrl string)(*CoreSavePageRequestBuilder) {
    return NewCoreSavePageRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
