// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coresavepage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use SavePagePostResponseable instead.
type SavePageResponse struct {
    SavePagePostResponse
}
// NewSavePageResponse instantiates a new SavePageResponse and sets the default values.
func NewSavePageResponse()(*SavePageResponse) {
    m := &SavePageResponse{
        SavePagePostResponse: *NewSavePagePostResponse(),
    }
    return m
}
// CreateSavePageResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSavePageResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSavePageResponse(), nil
}
// Deprecated: This class is obsolete. Use SavePagePostResponseable instead.
type SavePageResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    SavePagePostResponseable
}
