// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dokuwikigetpagelist

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GetPagelistPostRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The ns property
    ns *string
    //  [_default: `[]`_]
    opts *string
}
// NewGetPagelistPostRequestBody instantiates a new GetPagelistPostRequestBody and sets the default values.
func NewGetPagelistPostRequestBody()(*GetPagelistPostRequestBody) {
    m := &GetPagelistPostRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGetPagelistPostRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetPagelistPostRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetPagelistPostRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GetPagelistPostRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GetPagelistPostRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["ns"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNs(val)
        }
        return nil
    }
    res["opts"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOpts(val)
        }
        return nil
    }
    return res
}
// GetNs gets the ns property value. The ns property
// returns a *string when successful
func (m *GetPagelistPostRequestBody) GetNs()(*string) {
    return m.ns
}
// GetOpts gets the opts property value.  [_default: `[]`_]
// returns a *string when successful
func (m *GetPagelistPostRequestBody) GetOpts()(*string) {
    return m.opts
}
// Serialize serializes information the current object
func (m *GetPagelistPostRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("ns", m.GetNs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("opts", m.GetOpts())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GetPagelistPostRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetNs sets the ns property value. The ns property
func (m *GetPagelistPostRequestBody) SetNs(value *string)() {
    m.ns = value
}
// SetOpts sets the opts property value.  [_default: `[]`_]
func (m *GetPagelistPostRequestBody) SetOpts(value *string)() {
    m.opts = value
}
type GetPagelistPostRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetNs()(*string)
    GetOpts()(*string)
    SetNs(value *string)()
    SetOpts(value *string)()
}
