// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginaichatsimilar

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// PluginAichatSimilarRequestBuilder builds and executes requests for operations under \plugin.aichat.similar
type PluginAichatSimilarRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// PluginAichatSimilarRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type PluginAichatSimilarRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewPluginAichatSimilarRequestBuilderInternal instantiates a new PluginAichatSimilarRequestBuilder and sets the default values.
func NewPluginAichatSimilarRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginAichatSimilarRequestBuilder) {
    m := &PluginAichatSimilarRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/plugin.aichat.similar", pathParameters),
    }
    return m
}
// NewPluginAichatSimilarRequestBuilder instantiates a new PluginAichatSimilarRequestBuilder and sets the default values.
func NewPluginAichatSimilarRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginAichatSimilarRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewPluginAichatSimilarRequestBuilderInternal(urlParams, requestAdapter)
}
// Post uses the given query to find similar pages in the wiki. Returns the most similar chunks.This call returns chunks, not pages. So a page may returned multiple times when different chunks of itare similar to the query.Note that this call may return less results than requested depending on the used vector store.
// Deprecated: This method is obsolete. Use PostAsSimilarPostResponse instead.
// returns a SimilarResponseable when successful
func (m *PluginAichatSimilarRequestBuilder) Post(ctx context.Context, body SimilarPostRequestBodyable, requestConfiguration *PluginAichatSimilarRequestBuilderPostRequestConfiguration)(SimilarResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateSimilarResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(SimilarResponseable), nil
}
// PostAsSimilarPostResponse uses the given query to find similar pages in the wiki. Returns the most similar chunks.This call returns chunks, not pages. So a page may returned multiple times when different chunks of itare similar to the query.Note that this call may return less results than requested depending on the used vector store.
// returns a SimilarPostResponseable when successful
func (m *PluginAichatSimilarRequestBuilder) PostAsSimilarPostResponse(ctx context.Context, body SimilarPostRequestBodyable, requestConfiguration *PluginAichatSimilarRequestBuilderPostRequestConfiguration)(SimilarPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateSimilarPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(SimilarPostResponseable), nil
}
// ToPostRequestInformation uses the given query to find similar pages in the wiki. Returns the most similar chunks.This call returns chunks, not pages. So a page may returned multiple times when different chunks of itare similar to the query.Note that this call may return less results than requested depending on the used vector store.
// returns a *RequestInformation when successful
func (m *PluginAichatSimilarRequestBuilder) ToPostRequestInformation(ctx context.Context, body SimilarPostRequestBodyable, requestConfiguration *PluginAichatSimilarRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *PluginAichatSimilarRequestBuilder when successful
func (m *PluginAichatSimilarRequestBuilder) WithUrl(rawUrl string)(*PluginAichatSimilarRequestBuilder) {
    return NewPluginAichatSimilarRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
