// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginmoverenamemedia

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type RenameMediaPostRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The original media ID
    fromId *string
    // The new media ID
    toId *string
}
// NewRenameMediaPostRequestBody instantiates a new RenameMediaPostRequestBody and sets the default values.
func NewRenameMediaPostRequestBody()(*RenameMediaPostRequestBody) {
    m := &RenameMediaPostRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateRenameMediaPostRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRenameMediaPostRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewRenameMediaPostRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RenameMediaPostRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RenameMediaPostRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["fromId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFromId(val)
        }
        return nil
    }
    res["toId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetToId(val)
        }
        return nil
    }
    return res
}
// GetFromId gets the fromId property value. The original media ID
// returns a *string when successful
func (m *RenameMediaPostRequestBody) GetFromId()(*string) {
    return m.fromId
}
// GetToId gets the toId property value. The new media ID
// returns a *string when successful
func (m *RenameMediaPostRequestBody) GetToId()(*string) {
    return m.toId
}
// Serialize serializes information the current object
func (m *RenameMediaPostRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("fromId", m.GetFromId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("toId", m.GetToId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RenameMediaPostRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetFromId sets the fromId property value. The original media ID
func (m *RenameMediaPostRequestBody) SetFromId(value *string)() {
    m.fromId = value
}
// SetToId sets the toId property value. The new media ID
func (m *RenameMediaPostRequestBody) SetToId(value *string)() {
    m.toId = value
}
type RenameMediaPostRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFromId()(*string)
    GetToId()(*string)
    SetFromId(value *string)()
    SetToId(value *string)()
}
