// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dokuwikisetlocks

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use SetLocksPostResponseable instead.
type SetLocksResponse struct {
    SetLocksPostResponse
}
// NewSetLocksResponse instantiates a new SetLocksResponse and sets the default values.
func NewSetLocksResponse()(*SetLocksResponse) {
    m := &SetLocksResponse{
        SetLocksPostResponse: *NewSetLocksPostResponse(),
    }
    return m
}
// CreateSetLocksResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSetLocksResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSetLocksResponse(), nil
}
// Deprecated: This class is obsolete. Use SetLocksPostResponseable instead.
type SetLocksResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    SetLocksPostResponseable
}
