// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package wikigetattachmentinfo

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetAttachmentInfoPostResponseable instead.
type GetAttachmentInfoResponse struct {
    GetAttachmentInfoPostResponse
}
// NewGetAttachmentInfoResponse instantiates a new GetAttachmentInfoResponse and sets the default values.
func NewGetAttachmentInfoResponse()(*GetAttachmentInfoResponse) {
    m := &GetAttachmentInfoResponse{
        GetAttachmentInfoPostResponse: *NewGetAttachmentInfoPostResponse(),
    }
    return m
}
// CreateGetAttachmentInfoResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetAttachmentInfoResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetAttachmentInfoResponse(), nil
}
// Deprecated: This class is obsolete. Use GetAttachmentInfoPostResponseable instead.
type GetAttachmentInfoResponseable interface {
    GetAttachmentInfoPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
