// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginextensionuninstall

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// PluginExtensionUninstallRequestBuilder builds and executes requests for operations under \plugin.extension.uninstall
type PluginExtensionUninstallRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// PluginExtensionUninstallRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type PluginExtensionUninstallRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewPluginExtensionUninstallRequestBuilderInternal instantiates a new PluginExtensionUninstallRequestBuilder and sets the default values.
func NewPluginExtensionUninstallRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginExtensionUninstallRequestBuilder) {
    m := &PluginExtensionUninstallRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/plugin.extension.uninstall", pathParameters),
    }
    return m
}
// NewPluginExtensionUninstallRequestBuilder instantiates a new PluginExtensionUninstallRequestBuilder and sets the default values.
func NewPluginExtensionUninstallRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*PluginExtensionUninstallRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewPluginExtensionUninstallRequestBuilderInternal(urlParams, requestAdapter)
}
// Post uninstall a specific extension
// Deprecated: This method is obsolete. Use PostAsUninstallPostResponse instead.
// returns a UninstallResponseable when successful
func (m *PluginExtensionUninstallRequestBuilder) Post(ctx context.Context, body UninstallPostRequestBodyable, requestConfiguration *PluginExtensionUninstallRequestBuilderPostRequestConfiguration)(UninstallResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateUninstallResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(UninstallResponseable), nil
}
// PostAsUninstallPostResponse uninstall a specific extension
// returns a UninstallPostResponseable when successful
func (m *PluginExtensionUninstallRequestBuilder) PostAsUninstallPostResponse(ctx context.Context, body UninstallPostRequestBodyable, requestConfiguration *PluginExtensionUninstallRequestBuilderPostRequestConfiguration)(UninstallPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateUninstallPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(UninstallPostResponseable), nil
}
// returns a *RequestInformation when successful
func (m *PluginExtensionUninstallRequestBuilder) ToPostRequestInformation(ctx context.Context, body UninstallPostRequestBodyable, requestConfiguration *PluginExtensionUninstallRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *PluginExtensionUninstallRequestBuilder when successful
func (m *PluginExtensionUninstallRequestBuilder) WithUrl(rawUrl string)(*PluginExtensionUninstallRequestBuilder) {
    return NewPluginExtensionUninstallRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
