// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package corelistmedia

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ListMediaPostRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // How deep to search. 0 for all subnamespaces [_default: `1`_]
    depth *int32
    // Whether to include a MD5 hash of the media content [_default: `false`_]
    hash *bool
    // The namespace to search. Empty string for root namespace [_default: `""`_]
    namespace *string
    // A regular expression to filter the returned files [_default: `""`_]
    pattern *string
}
// NewListMediaPostRequestBody instantiates a new ListMediaPostRequestBody and sets the default values.
func NewListMediaPostRequestBody()(*ListMediaPostRequestBody) {
    m := &ListMediaPostRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateListMediaPostRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateListMediaPostRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewListMediaPostRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ListMediaPostRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDepth gets the depth property value. How deep to search. 0 for all subnamespaces [_default: `1`_]
// returns a *int32 when successful
func (m *ListMediaPostRequestBody) GetDepth()(*int32) {
    return m.depth
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ListMediaPostRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["depth"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDepth(val)
        }
        return nil
    }
    res["hash"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHash(val)
        }
        return nil
    }
    res["namespace"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNamespace(val)
        }
        return nil
    }
    res["pattern"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPattern(val)
        }
        return nil
    }
    return res
}
// GetHash gets the hash property value. Whether to include a MD5 hash of the media content [_default: `false`_]
// returns a *bool when successful
func (m *ListMediaPostRequestBody) GetHash()(*bool) {
    return m.hash
}
// GetNamespace gets the namespace property value. The namespace to search. Empty string for root namespace [_default: `""`_]
// returns a *string when successful
func (m *ListMediaPostRequestBody) GetNamespace()(*string) {
    return m.namespace
}
// GetPattern gets the pattern property value. A regular expression to filter the returned files [_default: `""`_]
// returns a *string when successful
func (m *ListMediaPostRequestBody) GetPattern()(*string) {
    return m.pattern
}
// Serialize serializes information the current object
func (m *ListMediaPostRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("depth", m.GetDepth())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("hash", m.GetHash())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("namespace", m.GetNamespace())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("pattern", m.GetPattern())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ListMediaPostRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDepth sets the depth property value. How deep to search. 0 for all subnamespaces [_default: `1`_]
func (m *ListMediaPostRequestBody) SetDepth(value *int32)() {
    m.depth = value
}
// SetHash sets the hash property value. Whether to include a MD5 hash of the media content [_default: `false`_]
func (m *ListMediaPostRequestBody) SetHash(value *bool)() {
    m.hash = value
}
// SetNamespace sets the namespace property value. The namespace to search. Empty string for root namespace [_default: `""`_]
func (m *ListMediaPostRequestBody) SetNamespace(value *string)() {
    m.namespace = value
}
// SetPattern sets the pattern property value. A regular expression to filter the returned files [_default: `""`_]
func (m *ListMediaPostRequestBody) SetPattern(value *string)() {
    m.pattern = value
}
type ListMediaPostRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDepth()(*int32)
    GetHash()(*bool)
    GetNamespace()(*string)
    GetPattern()(*string)
    SetDepth(value *int32)()
    SetHash(value *bool)()
    SetNamespace(value *string)()
    SetPattern(value *string)()
}
