// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package corelistmedia

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ListMediaPostResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Error object in case of an error
    error ListMediaPostResponse_errorable
    // The result property
    result []ListMediaPostResponse_resultable
}
// NewListMediaPostResponse instantiates a new ListMediaPostResponse and sets the default values.
func NewListMediaPostResponse()(*ListMediaPostResponse) {
    m := &ListMediaPostResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateListMediaPostResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateListMediaPostResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewListMediaPostResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ListMediaPostResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetError gets the error property value. Error object in case of an error
// returns a ListMediaPostResponse_errorable when successful
func (m *ListMediaPostResponse) GetError()(ListMediaPostResponse_errorable) {
    return m.error
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ListMediaPostResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["error"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateListMediaPostResponse_errorFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetError(val.(ListMediaPostResponse_errorable))
        }
        return nil
    }
    res["result"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateListMediaPostResponse_resultFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ListMediaPostResponse_resultable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ListMediaPostResponse_resultable)
                }
            }
            m.SetResult(res)
        }
        return nil
    }
    return res
}
// GetResult gets the result property value. The result property
// returns a []ListMediaPostResponse_resultable when successful
func (m *ListMediaPostResponse) GetResult()([]ListMediaPostResponse_resultable) {
    return m.result
}
// Serialize serializes information the current object
func (m *ListMediaPostResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("error", m.GetError())
        if err != nil {
            return err
        }
    }
    if m.GetResult() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetResult()))
        for i, v := range m.GetResult() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("result", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ListMediaPostResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetError sets the error property value. Error object in case of an error
func (m *ListMediaPostResponse) SetError(value ListMediaPostResponse_errorable)() {
    m.error = value
}
// SetResult sets the result property value. The result property
func (m *ListMediaPostResponse) SetResult(value []ListMediaPostResponse_resultable)() {
    m.result = value
}
type ListMediaPostResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetError()(ListMediaPostResponse_errorable)
    GetResult()([]ListMediaPostResponse_resultable)
    SetError(value ListMediaPostResponse_errorable)()
    SetResult(value []ListMediaPostResponse_resultable)()
}
