// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package corelistmedia

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ListMediaPostResponseable instead.
type ListMediaResponse struct {
    ListMediaPostResponse
}
// NewListMediaResponse instantiates a new ListMediaResponse and sets the default values.
func NewListMediaResponse()(*ListMediaResponse) {
    m := &ListMediaResponse{
        ListMediaPostResponse: *NewListMediaPostResponse(),
    }
    return m
}
// CreateListMediaResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateListMediaResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewListMediaResponse(), nil
}
// Deprecated: This class is obsolete. Use ListMediaPostResponseable instead.
type ListMediaResponseable interface {
    ListMediaPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
