// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coregetapiversion

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// CoreGetAPIVersionRequestBuilder builds and executes requests for operations under \core.getAPIVersion
type CoreGetAPIVersionRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CoreGetAPIVersionRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CoreGetAPIVersionRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewCoreGetAPIVersionRequestBuilderInternal instantiates a new CoreGetAPIVersionRequestBuilder and sets the default values.
func NewCoreGetAPIVersionRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreGetAPIVersionRequestBuilder) {
    m := &CoreGetAPIVersionRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/core.getAPIVersion", pathParameters),
    }
    return m
}
// NewCoreGetAPIVersionRequestBuilder instantiates a new CoreGetAPIVersionRequestBuilder and sets the default values.
func NewCoreGetAPIVersionRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreGetAPIVersionRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCoreGetAPIVersionRequestBuilderInternal(urlParams, requestAdapter)
}
// Post this method is public and does not require authentication. This is the version of the DokuWiki API. It increases whenever the API definition changes.When developing a client, you should check this version and make sure you can handle it.
// Deprecated: This method is obsolete. Use PostAsGetAPIVersionPostResponse instead.
// returns a GetAPIVersionResponseable when successful
func (m *CoreGetAPIVersionRequestBuilder) Post(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *CoreGetAPIVersionRequestBuilderPostRequestConfiguration)(GetAPIVersionResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetAPIVersionResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetAPIVersionResponseable), nil
}
// PostAsGetAPIVersionPostResponse this method is public and does not require authentication. This is the version of the DokuWiki API. It increases whenever the API definition changes.When developing a client, you should check this version and make sure you can handle it.
// returns a GetAPIVersionPostResponseable when successful
func (m *CoreGetAPIVersionRequestBuilder) PostAsGetAPIVersionPostResponse(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *CoreGetAPIVersionRequestBuilderPostRequestConfiguration)(GetAPIVersionPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetAPIVersionPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetAPIVersionPostResponseable), nil
}
// ToPostRequestInformation this method is public and does not require authentication. This is the version of the DokuWiki API. It increases whenever the API definition changes.When developing a client, you should check this version and make sure you can handle it.
// returns a *RequestInformation when successful
func (m *CoreGetAPIVersionRequestBuilder) ToPostRequestInformation(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *CoreGetAPIVersionRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    requestInfo.SetContentFromScalar(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CoreGetAPIVersionRequestBuilder when successful
func (m *CoreGetAPIVersionRequestBuilder) WithUrl(rawUrl string)(*CoreGetAPIVersionRequestBuilder) {
    return NewCoreGetAPIVersionRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
