// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coregetapiversion

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetAPIVersionPostResponseable instead.
type GetAPIVersionResponse struct {
    GetAPIVersionPostResponse
}
// NewGetAPIVersionResponse instantiates a new GetAPIVersionResponse and sets the default values.
func NewGetAPIVersionResponse()(*GetAPIVersionResponse) {
    m := &GetAPIVersionResponse{
        GetAPIVersionPostResponse: *NewGetAPIVersionPostResponse(),
    }
    return m
}
// CreateGetAPIVersionResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetAPIVersionResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetAPIVersionResponse(), nil
}
// Deprecated: This class is obsolete. Use GetAPIVersionPostResponseable instead.
type GetAPIVersionResponseable interface {
    GetAPIVersionPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
