// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coregetpage

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GetPagePostRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // wiki page id
    page *string
    // Revision timestamp to access an older revision [_default: `0`_]
    rev *int32
}
// NewGetPagePostRequestBody instantiates a new GetPagePostRequestBody and sets the default values.
func NewGetPagePostRequestBody()(*GetPagePostRequestBody) {
    m := &GetPagePostRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGetPagePostRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetPagePostRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetPagePostRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GetPagePostRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GetPagePostRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["page"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPage(val)
        }
        return nil
    }
    res["rev"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRev(val)
        }
        return nil
    }
    return res
}
// GetPage gets the page property value. wiki page id
// returns a *string when successful
func (m *GetPagePostRequestBody) GetPage()(*string) {
    return m.page
}
// GetRev gets the rev property value. Revision timestamp to access an older revision [_default: `0`_]
// returns a *int32 when successful
func (m *GetPagePostRequestBody) GetRev()(*int32) {
    return m.rev
}
// Serialize serializes information the current object
func (m *GetPagePostRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("page", m.GetPage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("rev", m.GetRev())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GetPagePostRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetPage sets the page property value. wiki page id
func (m *GetPagePostRequestBody) SetPage(value *string)() {
    m.page = value
}
// SetRev sets the rev property value. Revision timestamp to access an older revision [_default: `0`_]
func (m *GetPagePostRequestBody) SetRev(value *int32)() {
    m.rev = value
}
type GetPagePostRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPage()(*string)
    GetRev()(*int32)
    SetPage(value *string)()
    SetRev(value *int32)()
}
