// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coreappendpage

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CoreAppendPageRequestBuilder builds and executes requests for operations under \core.appendPage
type CoreAppendPageRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CoreAppendPageRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CoreAppendPageRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewCoreAppendPageRequestBuilderInternal instantiates a new CoreAppendPageRequestBuilder and sets the default values.
func NewCoreAppendPageRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreAppendPageRequestBuilder) {
    m := &CoreAppendPageRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/core.appendPage", pathParameters),
    }
    return m
}
// NewCoreAppendPageRequestBuilder instantiates a new CoreAppendPageRequestBuilder and sets the default values.
func NewCoreAppendPageRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreAppendPageRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCoreAppendPageRequestBuilderInternal(urlParams, requestAdapter)
}
// Post if the page does not exist, it will be created. If a page template for the non-existantpage is configured, the given text will appended to that template.The call will create a new page revision.You need write permissions for the given page.
// Deprecated: This method is obsolete. Use PostAsAppendPagePostResponse instead.
// returns a AppendPageResponseable when successful
func (m *CoreAppendPageRequestBuilder) Post(ctx context.Context, body AppendPagePostRequestBodyable, requestConfiguration *CoreAppendPageRequestBuilderPostRequestConfiguration)(AppendPageResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateAppendPageResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(AppendPageResponseable), nil
}
// PostAsAppendPagePostResponse if the page does not exist, it will be created. If a page template for the non-existantpage is configured, the given text will appended to that template.The call will create a new page revision.You need write permissions for the given page.
// returns a AppendPagePostResponseable when successful
func (m *CoreAppendPageRequestBuilder) PostAsAppendPagePostResponse(ctx context.Context, body AppendPagePostRequestBodyable, requestConfiguration *CoreAppendPageRequestBuilderPostRequestConfiguration)(AppendPagePostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateAppendPagePostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(AppendPagePostResponseable), nil
}
// ToPostRequestInformation if the page does not exist, it will be created. If a page template for the non-existantpage is configured, the given text will appended to that template.The call will create a new page revision.You need write permissions for the given page.
// returns a *RequestInformation when successful
func (m *CoreAppendPageRequestBuilder) ToPostRequestInformation(ctx context.Context, body AppendPagePostRequestBodyable, requestConfiguration *CoreAppendPageRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CoreAppendPageRequestBuilder when successful
func (m *CoreAppendPageRequestBuilder) WithUrl(rawUrl string)(*CoreAppendPageRequestBuilder) {
    return NewCoreAppendPageRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
