// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package pluginacllistacls

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ListAclsPostResponseable instead.
type ListAclsResponse struct {
    ListAclsPostResponse
}
// NewListAclsResponse instantiates a new ListAclsResponse and sets the default values.
func NewListAclsResponse()(*ListAclsResponse) {
    m := &ListAclsResponse{
        ListAclsPostResponse: *NewListAclsPostResponse(),
    }
    return m
}
// CreateListAclsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateListAclsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewListAclsResponse(), nil
}
// Deprecated: This class is obsolete. Use ListAclsPostResponseable instead.
type ListAclsResponseable interface {
    ListAclsPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
