// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package corelogoff

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// CoreLogoffRequestBuilder builds and executes requests for operations under \core.logoff
type CoreLogoffRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CoreLogoffRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CoreLogoffRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewCoreLogoffRequestBuilderInternal instantiates a new CoreLogoffRequestBuilder and sets the default values.
func NewCoreLogoffRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreLogoffRequestBuilder) {
    m := &CoreLogoffRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/core.logoff", pathParameters),
    }
    return m
}
// NewCoreLogoffRequestBuilder instantiates a new CoreLogoffRequestBuilder and sets the default values.
func NewCoreLogoffRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreLogoffRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCoreLogoffRequestBuilderInternal(urlParams, requestAdapter)
}
// Post attempt to log out the current user, deleting the appropriate cookiesUse of this mechanism is discouraged. Using token authentication is preferred.
// Deprecated: This method is obsolete. Use PostAsLogoffPostResponse instead.
// returns a LogoffResponseable when successful
func (m *CoreLogoffRequestBuilder) Post(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *CoreLogoffRequestBuilderPostRequestConfiguration)(LogoffResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateLogoffResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(LogoffResponseable), nil
}
// PostAsLogoffPostResponse attempt to log out the current user, deleting the appropriate cookiesUse of this mechanism is discouraged. Using token authentication is preferred.
// returns a LogoffPostResponseable when successful
func (m *CoreLogoffRequestBuilder) PostAsLogoffPostResponse(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *CoreLogoffRequestBuilderPostRequestConfiguration)(LogoffPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateLogoffPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(LogoffPostResponseable), nil
}
// ToPostRequestInformation attempt to log out the current user, deleting the appropriate cookiesUse of this mechanism is discouraged. Using token authentication is preferred.
// returns a *RequestInformation when successful
func (m *CoreLogoffRequestBuilder) ToPostRequestInformation(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *CoreLogoffRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    requestInfo.SetContentFromScalar(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CoreLogoffRequestBuilder when successful
func (m *CoreLogoffRequestBuilder) WithUrl(rawUrl string)(*CoreLogoffRequestBuilder) {
    return NewCoreLogoffRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
