// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coregetwikititle

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetWikiTitlePostResponseable instead.
type GetWikiTitleResponse struct {
    GetWikiTitlePostResponse
}
// NewGetWikiTitleResponse instantiates a new GetWikiTitleResponse and sets the default values.
func NewGetWikiTitleResponse()(*GetWikiTitleResponse) {
    m := &GetWikiTitleResponse{
        GetWikiTitlePostResponse: *NewGetWikiTitlePostResponse(),
    }
    return m
}
// CreateGetWikiTitleResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetWikiTitleResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetWikiTitleResponse(), nil
}
// Deprecated: This class is obsolete. Use GetWikiTitlePostResponseable instead.
type GetWikiTitleResponseable interface {
    GetWikiTitlePostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
