// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package wikigetrpcversionsupported

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use GetRPCVersionSupportedPostResponseable instead.
type GetRPCVersionSupportedResponse struct {
    GetRPCVersionSupportedPostResponse
}
// NewGetRPCVersionSupportedResponse instantiates a new GetRPCVersionSupportedResponse and sets the default values.
func NewGetRPCVersionSupportedResponse()(*GetRPCVersionSupportedResponse) {
    m := &GetRPCVersionSupportedResponse{
        GetRPCVersionSupportedPostResponse: *NewGetRPCVersionSupportedPostResponse(),
    }
    return m
}
// CreateGetRPCVersionSupportedResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetRPCVersionSupportedResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetRPCVersionSupportedResponse(), nil
}
// Deprecated: This class is obsolete. Use GetRPCVersionSupportedPostResponseable instead.
type GetRPCVersionSupportedResponseable interface {
    GetRPCVersionSupportedPostResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
