// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package wikigetrpcversionsupported

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// WikiGetRPCVersionSupportedRequestBuilder builds and executes requests for operations under \wiki.getRPCVersionSupported
type WikiGetRPCVersionSupportedRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// WikiGetRPCVersionSupportedRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type WikiGetRPCVersionSupportedRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewWikiGetRPCVersionSupportedRequestBuilderInternal instantiates a new WikiGetRPCVersionSupportedRequestBuilder and sets the default values.
func NewWikiGetRPCVersionSupportedRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WikiGetRPCVersionSupportedRequestBuilder) {
    m := &WikiGetRPCVersionSupportedRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/wiki.getRPCVersionSupported", pathParameters),
    }
    return m
}
// NewWikiGetRPCVersionSupportedRequestBuilder instantiates a new WikiGetRPCVersionSupportedRequestBuilder and sets the default values.
func NewWikiGetRPCVersionSupportedRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WikiGetRPCVersionSupportedRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewWikiGetRPCVersionSupportedRequestBuilderInternal(urlParams, requestAdapter)
}
// Post **This method is deprecated.** Wiki RPC spec is no longer supportedThis method is public and does not require authentication. 
// Deprecated: This method is obsolete. Use PostAsGetRPCVersionSupportedPostResponse instead.
// returns a GetRPCVersionSupportedResponseable when successful
func (m *WikiGetRPCVersionSupportedRequestBuilder) Post(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *WikiGetRPCVersionSupportedRequestBuilderPostRequestConfiguration)(GetRPCVersionSupportedResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetRPCVersionSupportedResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetRPCVersionSupportedResponseable), nil
}
// PostAsGetRPCVersionSupportedPostResponse **This method is deprecated.** Wiki RPC spec is no longer supportedThis method is public and does not require authentication. 
// Deprecated: 
// returns a GetRPCVersionSupportedPostResponseable when successful
func (m *WikiGetRPCVersionSupportedRequestBuilder) PostAsGetRPCVersionSupportedPostResponse(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *WikiGetRPCVersionSupportedRequestBuilderPostRequestConfiguration)(GetRPCVersionSupportedPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetRPCVersionSupportedPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetRPCVersionSupportedPostResponseable), nil
}
// ToPostRequestInformation **This method is deprecated.** Wiki RPC spec is no longer supportedThis method is public and does not require authentication. 
// Deprecated: 
// returns a *RequestInformation when successful
func (m *WikiGetRPCVersionSupportedRequestBuilder) ToPostRequestInformation(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *WikiGetRPCVersionSupportedRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    requestInfo.SetContentFromScalar(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// Deprecated: 
// returns a *WikiGetRPCVersionSupportedRequestBuilder when successful
func (m *WikiGetRPCVersionSupportedRequestBuilder) WithUrl(rawUrl string)(*WikiGetRPCVersionSupportedRequestBuilder) {
    return NewWikiGetRPCVersionSupportedRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
