// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package wikigetallpages

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// WikiGetAllPagesRequestBuilder builds and executes requests for operations under \wiki.getAllPages
type WikiGetAllPagesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// WikiGetAllPagesRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type WikiGetAllPagesRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewWikiGetAllPagesRequestBuilderInternal instantiates a new WikiGetAllPagesRequestBuilder and sets the default values.
func NewWikiGetAllPagesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WikiGetAllPagesRequestBuilder) {
    m := &WikiGetAllPagesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/wiki.getAllPages", pathParameters),
    }
    return m
}
// NewWikiGetAllPagesRequestBuilder instantiates a new WikiGetAllPagesRequestBuilder and sets the default values.
func NewWikiGetAllPagesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WikiGetAllPagesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewWikiGetAllPagesRequestBuilderInternal(urlParams, requestAdapter)
}
// Post **This method is deprecated.** use core.listPages instead
// Deprecated: This method is obsolete. Use PostAsGetAllPagesPostResponse instead.
// returns a GetAllPagesResponseable when successful
func (m *WikiGetAllPagesRequestBuilder) Post(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *WikiGetAllPagesRequestBuilderPostRequestConfiguration)(GetAllPagesResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetAllPagesResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetAllPagesResponseable), nil
}
// PostAsGetAllPagesPostResponse **This method is deprecated.** use core.listPages instead
// Deprecated: 
// returns a GetAllPagesPostResponseable when successful
func (m *WikiGetAllPagesRequestBuilder) PostAsGetAllPagesPostResponse(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *WikiGetAllPagesRequestBuilderPostRequestConfiguration)(GetAllPagesPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateGetAllPagesPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(GetAllPagesPostResponseable), nil
}
// ToPostRequestInformation **This method is deprecated.** use core.listPages instead
// Deprecated: 
// returns a *RequestInformation when successful
func (m *WikiGetAllPagesRequestBuilder) ToPostRequestInformation(ctx context.Context, body i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable, requestConfiguration *WikiGetAllPagesRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    requestInfo.SetContentFromScalar(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// Deprecated: 
// returns a *WikiGetAllPagesRequestBuilder when successful
func (m *WikiGetAllPagesRequestBuilder) WithUrl(rawUrl string)(*WikiGetAllPagesRequestBuilder) {
    return NewWikiGetAllPagesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
