// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package corelogin

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CoreLoginRequestBuilder builds and executes requests for operations under \core.login
type CoreLoginRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// CoreLoginRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type CoreLoginRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewCoreLoginRequestBuilderInternal instantiates a new CoreLoginRequestBuilder and sets the default values.
func NewCoreLoginRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreLoginRequestBuilder) {
    m := &CoreLoginRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/core.login", pathParameters),
    }
    return m
}
// NewCoreLoginRequestBuilder instantiates a new CoreLoginRequestBuilder and sets the default values.
func NewCoreLoginRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*CoreLoginRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewCoreLoginRequestBuilderInternal(urlParams, requestAdapter)
}
// Post this method is public and does not require authentication. This will use the given credentials and attempt to login the user. This will set theappropriate cookies, which can be used for subsequent requests.Use of this mechanism is discouraged. Using token authentication is preferred.
// Deprecated: This method is obsolete. Use PostAsLoginPostResponse instead.
// returns a LoginResponseable when successful
func (m *CoreLoginRequestBuilder) Post(ctx context.Context, body LoginPostRequestBodyable, requestConfiguration *CoreLoginRequestBuilderPostRequestConfiguration)(LoginResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateLoginResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(LoginResponseable), nil
}
// PostAsLoginPostResponse this method is public and does not require authentication. This will use the given credentials and attempt to login the user. This will set theappropriate cookies, which can be used for subsequent requests.Use of this mechanism is discouraged. Using token authentication is preferred.
// returns a LoginPostResponseable when successful
func (m *CoreLoginRequestBuilder) PostAsLoginPostResponse(ctx context.Context, body LoginPostRequestBodyable, requestConfiguration *CoreLoginRequestBuilderPostRequestConfiguration)(LoginPostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateLoginPostResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(LoginPostResponseable), nil
}
// ToPostRequestInformation this method is public and does not require authentication. This will use the given credentials and attempt to login the user. This will set theappropriate cookies, which can be used for subsequent requests.Use of this mechanism is discouraged. Using token authentication is preferred.
// returns a *RequestInformation when successful
func (m *CoreLoginRequestBuilder) ToPostRequestInformation(ctx context.Context, body LoginPostRequestBodyable, requestConfiguration *CoreLoginRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CoreLoginRequestBuilder when successful
func (m *CoreLoginRequestBuilder) WithUrl(rawUrl string)(*CoreLoginRequestBuilder) {
    return NewCoreLoginRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
