/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoreGetPageHTMLRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreGetPageHTMLRequest{}

// CoreGetPageHTMLRequest struct for CoreGetPageHTMLRequest
type CoreGetPageHTMLRequest struct {
	// page id
	Page string `json:"page"`
	// revision timestamp [_default: `0`_]
	Rev *int32 `json:"rev,omitempty"`
}

type _CoreGetPageHTMLRequest CoreGetPageHTMLRequest

// NewCoreGetPageHTMLRequest instantiates a new CoreGetPageHTMLRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreGetPageHTMLRequest(page string) *CoreGetPageHTMLRequest {
	this := CoreGetPageHTMLRequest{}
	this.Page = page
	return &this
}

// NewCoreGetPageHTMLRequestWithDefaults instantiates a new CoreGetPageHTMLRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreGetPageHTMLRequestWithDefaults() *CoreGetPageHTMLRequest {
	this := CoreGetPageHTMLRequest{}
	return &this
}

// GetPage returns the Page field value
func (o *CoreGetPageHTMLRequest) GetPage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *CoreGetPageHTMLRequest) GetPageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *CoreGetPageHTMLRequest) SetPage(v string) {
	o.Page = v
}

// GetRev returns the Rev field value if set, zero value otherwise.
func (o *CoreGetPageHTMLRequest) GetRev() int32 {
	if o == nil || IsNil(o.Rev) {
		var ret int32
		return ret
	}
	return *o.Rev
}

// GetRevOk returns a tuple with the Rev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreGetPageHTMLRequest) GetRevOk() (*int32, bool) {
	if o == nil || IsNil(o.Rev) {
		return nil, false
	}
	return o.Rev, true
}

// HasRev returns a boolean if a field has been set.
func (o *CoreGetPageHTMLRequest) HasRev() bool {
	if o != nil && !IsNil(o.Rev) {
		return true
	}

	return false
}

// SetRev gets a reference to the given int32 and assigns it to the Rev field.
func (o *CoreGetPageHTMLRequest) SetRev(v int32) {
	o.Rev = &v
}

func (o CoreGetPageHTMLRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreGetPageHTMLRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	if !IsNil(o.Rev) {
		toSerialize["rev"] = o.Rev
	}
	return toSerialize, nil
}

func (o *CoreGetPageHTMLRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoreGetPageHTMLRequest := _CoreGetPageHTMLRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoreGetPageHTMLRequest)

	if err != nil {
		return err
	}

	*o = CoreGetPageHTMLRequest(varCoreGetPageHTMLRequest)

	return err
}

type NullableCoreGetPageHTMLRequest struct {
	value *CoreGetPageHTMLRequest
	isSet bool
}

func (v NullableCoreGetPageHTMLRequest) Get() *CoreGetPageHTMLRequest {
	return v.value
}

func (v *NullableCoreGetPageHTMLRequest) Set(val *CoreGetPageHTMLRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreGetPageHTMLRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreGetPageHTMLRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreGetPageHTMLRequest(val *CoreGetPageHTMLRequest) *NullableCoreGetPageHTMLRequest {
	return &NullableCoreGetPageHTMLRequest{value: val, isSet: true}
}

func (v NullableCoreGetPageHTMLRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreGetPageHTMLRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


