/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoreGetMediaInfoRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreGetMediaInfoRequest{}

// CoreGetMediaInfoRequest struct for CoreGetMediaInfoRequest
type CoreGetMediaInfoRequest struct {
	// file id
	Media string `json:"media"`
	// revision timestamp [_default: `0`_]
	Rev *int32 `json:"rev,omitempty"`
	// whether to include the author information [_default: `false`_]
	Author *bool `json:"author,omitempty"`
	// whether to include the MD5 hash of the media content [_default: `false`_]
	Hash *bool `json:"hash,omitempty"`
}

type _CoreGetMediaInfoRequest CoreGetMediaInfoRequest

// NewCoreGetMediaInfoRequest instantiates a new CoreGetMediaInfoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreGetMediaInfoRequest(media string) *CoreGetMediaInfoRequest {
	this := CoreGetMediaInfoRequest{}
	this.Media = media
	return &this
}

// NewCoreGetMediaInfoRequestWithDefaults instantiates a new CoreGetMediaInfoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreGetMediaInfoRequestWithDefaults() *CoreGetMediaInfoRequest {
	this := CoreGetMediaInfoRequest{}
	return &this
}

// GetMedia returns the Media field value
func (o *CoreGetMediaInfoRequest) GetMedia() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Media
}

// GetMediaOk returns a tuple with the Media field value
// and a boolean to check if the value has been set.
func (o *CoreGetMediaInfoRequest) GetMediaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Media, true
}

// SetMedia sets field value
func (o *CoreGetMediaInfoRequest) SetMedia(v string) {
	o.Media = v
}

// GetRev returns the Rev field value if set, zero value otherwise.
func (o *CoreGetMediaInfoRequest) GetRev() int32 {
	if o == nil || IsNil(o.Rev) {
		var ret int32
		return ret
	}
	return *o.Rev
}

// GetRevOk returns a tuple with the Rev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreGetMediaInfoRequest) GetRevOk() (*int32, bool) {
	if o == nil || IsNil(o.Rev) {
		return nil, false
	}
	return o.Rev, true
}

// HasRev returns a boolean if a field has been set.
func (o *CoreGetMediaInfoRequest) HasRev() bool {
	if o != nil && !IsNil(o.Rev) {
		return true
	}

	return false
}

// SetRev gets a reference to the given int32 and assigns it to the Rev field.
func (o *CoreGetMediaInfoRequest) SetRev(v int32) {
	o.Rev = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *CoreGetMediaInfoRequest) GetAuthor() bool {
	if o == nil || IsNil(o.Author) {
		var ret bool
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreGetMediaInfoRequest) GetAuthorOk() (*bool, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *CoreGetMediaInfoRequest) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given bool and assigns it to the Author field.
func (o *CoreGetMediaInfoRequest) SetAuthor(v bool) {
	o.Author = &v
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *CoreGetMediaInfoRequest) GetHash() bool {
	if o == nil || IsNil(o.Hash) {
		var ret bool
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreGetMediaInfoRequest) GetHashOk() (*bool, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *CoreGetMediaInfoRequest) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given bool and assigns it to the Hash field.
func (o *CoreGetMediaInfoRequest) SetHash(v bool) {
	o.Hash = &v
}

func (o CoreGetMediaInfoRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreGetMediaInfoRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["media"] = o.Media
	if !IsNil(o.Rev) {
		toSerialize["rev"] = o.Rev
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	return toSerialize, nil
}

func (o *CoreGetMediaInfoRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"media",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoreGetMediaInfoRequest := _CoreGetMediaInfoRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoreGetMediaInfoRequest)

	if err != nil {
		return err
	}

	*o = CoreGetMediaInfoRequest(varCoreGetMediaInfoRequest)

	return err
}

type NullableCoreGetMediaInfoRequest struct {
	value *CoreGetMediaInfoRequest
	isSet bool
}

func (v NullableCoreGetMediaInfoRequest) Get() *CoreGetMediaInfoRequest {
	return v.value
}

func (v *NullableCoreGetMediaInfoRequest) Set(val *CoreGetMediaInfoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreGetMediaInfoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreGetMediaInfoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreGetMediaInfoRequest(val *CoreGetMediaInfoRequest) *NullableCoreGetMediaInfoRequest {
	return &NullableCoreGetMediaInfoRequest{value: val, isSet: true}
}

func (v NullableCoreGetMediaInfoRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreGetMediaInfoRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


