/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
)

// checks if the PluginAichatSimilar200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginAichatSimilar200Response{}

// PluginAichatSimilar200Response struct for PluginAichatSimilar200Response
type PluginAichatSimilar200Response struct {
	// A list of similar chunks
	Result []PluginAichatAsk200ResponseResultSourcesInner `json:"result,omitempty"`
	Error *CoreGetAPIVersion200ResponseError `json:"error,omitempty"`
}

// NewPluginAichatSimilar200Response instantiates a new PluginAichatSimilar200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginAichatSimilar200Response() *PluginAichatSimilar200Response {
	this := PluginAichatSimilar200Response{}
	return &this
}

// NewPluginAichatSimilar200ResponseWithDefaults instantiates a new PluginAichatSimilar200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginAichatSimilar200ResponseWithDefaults() *PluginAichatSimilar200Response {
	this := PluginAichatSimilar200Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *PluginAichatSimilar200Response) GetResult() []PluginAichatAsk200ResponseResultSourcesInner {
	if o == nil || IsNil(o.Result) {
		var ret []PluginAichatAsk200ResponseResultSourcesInner
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginAichatSimilar200Response) GetResultOk() ([]PluginAichatAsk200ResponseResultSourcesInner, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *PluginAichatSimilar200Response) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []PluginAichatAsk200ResponseResultSourcesInner and assigns it to the Result field.
func (o *PluginAichatSimilar200Response) SetResult(v []PluginAichatAsk200ResponseResultSourcesInner) {
	o.Result = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PluginAichatSimilar200Response) GetError() CoreGetAPIVersion200ResponseError {
	if o == nil || IsNil(o.Error) {
		var ret CoreGetAPIVersion200ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginAichatSimilar200Response) GetErrorOk() (*CoreGetAPIVersion200ResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PluginAichatSimilar200Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given CoreGetAPIVersion200ResponseError and assigns it to the Error field.
func (o *PluginAichatSimilar200Response) SetError(v CoreGetAPIVersion200ResponseError) {
	o.Error = &v
}

func (o PluginAichatSimilar200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginAichatSimilar200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullablePluginAichatSimilar200Response struct {
	value *PluginAichatSimilar200Response
	isSet bool
}

func (v NullablePluginAichatSimilar200Response) Get() *PluginAichatSimilar200Response {
	return v.value
}

func (v *NullablePluginAichatSimilar200Response) Set(val *PluginAichatSimilar200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginAichatSimilar200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginAichatSimilar200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginAichatSimilar200Response(val *PluginAichatSimilar200Response) *NullablePluginAichatSimilar200Response {
	return &NullablePluginAichatSimilar200Response{value: val, isSet: true}
}

func (v NullablePluginAichatSimilar200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginAichatSimilar200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


