/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
)

// checks if the PluginMoveRenamePage200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginMoveRenamePage200Response{}

// PluginMoveRenamePage200Response struct for PluginMoveRenamePage200Response
type PluginMoveRenamePage200Response struct {
	// Always true when no error occured
	Result *bool `json:"result,omitempty"`
	Error *CoreGetAPIVersion200ResponseError `json:"error,omitempty"`
}

// NewPluginMoveRenamePage200Response instantiates a new PluginMoveRenamePage200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginMoveRenamePage200Response() *PluginMoveRenamePage200Response {
	this := PluginMoveRenamePage200Response{}
	return &this
}

// NewPluginMoveRenamePage200ResponseWithDefaults instantiates a new PluginMoveRenamePage200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginMoveRenamePage200ResponseWithDefaults() *PluginMoveRenamePage200Response {
	this := PluginMoveRenamePage200Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *PluginMoveRenamePage200Response) GetResult() bool {
	if o == nil || IsNil(o.Result) {
		var ret bool
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginMoveRenamePage200Response) GetResultOk() (*bool, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *PluginMoveRenamePage200Response) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given bool and assigns it to the Result field.
func (o *PluginMoveRenamePage200Response) SetResult(v bool) {
	o.Result = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PluginMoveRenamePage200Response) GetError() CoreGetAPIVersion200ResponseError {
	if o == nil || IsNil(o.Error) {
		var ret CoreGetAPIVersion200ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginMoveRenamePage200Response) GetErrorOk() (*CoreGetAPIVersion200ResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PluginMoveRenamePage200Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given CoreGetAPIVersion200ResponseError and assigns it to the Error field.
func (o *PluginMoveRenamePage200Response) SetError(v CoreGetAPIVersion200ResponseError) {
	o.Error = &v
}

func (o PluginMoveRenamePage200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginMoveRenamePage200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullablePluginMoveRenamePage200Response struct {
	value *PluginMoveRenamePage200Response
	isSet bool
}

func (v NullablePluginMoveRenamePage200Response) Get() *PluginMoveRenamePage200Response {
	return v.value
}

func (v *NullablePluginMoveRenamePage200Response) Set(val *PluginMoveRenamePage200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginMoveRenamePage200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginMoveRenamePage200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginMoveRenamePage200Response(val *PluginMoveRenamePage200Response) *NullablePluginMoveRenamePage200Response {
	return &NullablePluginMoveRenamePage200Response{value: val, isSet: true}
}

func (v NullablePluginMoveRenamePage200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginMoveRenamePage200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


