/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
)

// checks if the CoreGetMediaInfo200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreGetMediaInfo200Response{}

// CoreGetMediaInfo200Response struct for CoreGetMediaInfo200Response
type CoreGetMediaInfo200Response struct {
	Result *CoreGetMediaInfo200ResponseResult `json:"result,omitempty"`
	Error *CoreGetAPIVersion200ResponseError `json:"error,omitempty"`
}

// NewCoreGetMediaInfo200Response instantiates a new CoreGetMediaInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreGetMediaInfo200Response() *CoreGetMediaInfo200Response {
	this := CoreGetMediaInfo200Response{}
	return &this
}

// NewCoreGetMediaInfo200ResponseWithDefaults instantiates a new CoreGetMediaInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreGetMediaInfo200ResponseWithDefaults() *CoreGetMediaInfo200Response {
	this := CoreGetMediaInfo200Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CoreGetMediaInfo200Response) GetResult() CoreGetMediaInfo200ResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret CoreGetMediaInfo200ResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreGetMediaInfo200Response) GetResultOk() (*CoreGetMediaInfo200ResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CoreGetMediaInfo200Response) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given CoreGetMediaInfo200ResponseResult and assigns it to the Result field.
func (o *CoreGetMediaInfo200Response) SetResult(v CoreGetMediaInfo200ResponseResult) {
	o.Result = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CoreGetMediaInfo200Response) GetError() CoreGetAPIVersion200ResponseError {
	if o == nil || IsNil(o.Error) {
		var ret CoreGetAPIVersion200ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreGetMediaInfo200Response) GetErrorOk() (*CoreGetAPIVersion200ResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CoreGetMediaInfo200Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given CoreGetAPIVersion200ResponseError and assigns it to the Error field.
func (o *CoreGetMediaInfo200Response) SetError(v CoreGetAPIVersion200ResponseError) {
	o.Error = &v
}

func (o CoreGetMediaInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreGetMediaInfo200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableCoreGetMediaInfo200Response struct {
	value *CoreGetMediaInfo200Response
	isSet bool
}

func (v NullableCoreGetMediaInfo200Response) Get() *CoreGetMediaInfo200Response {
	return v.value
}

func (v *NullableCoreGetMediaInfo200Response) Set(val *CoreGetMediaInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreGetMediaInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreGetMediaInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreGetMediaInfo200Response(val *CoreGetMediaInfo200Response) *NullableCoreGetMediaInfo200Response {
	return &NullableCoreGetMediaInfo200Response{value: val, isSet: true}
}

func (v NullableCoreGetMediaInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreGetMediaInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


