/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PluginAichatAskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginAichatAskRequest{}

// PluginAichatAskRequest struct for PluginAichatAskRequest
type PluginAichatAskRequest struct {
	// The question to ask the LLM
	Query string `json:"query"`
	// The model to use, if empty the default model is used [_default: `\"\"`_]
	Model *string `json:"model,omitempty"`
	// Language code to override preferUIlanguage setting. \"auto\" to force autodetection. [_default: `\"\"`_]
	Lang *string `json:"lang,omitempty"`
}

type _PluginAichatAskRequest PluginAichatAskRequest

// NewPluginAichatAskRequest instantiates a new PluginAichatAskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginAichatAskRequest(query string) *PluginAichatAskRequest {
	this := PluginAichatAskRequest{}
	this.Query = query
	return &this
}

// NewPluginAichatAskRequestWithDefaults instantiates a new PluginAichatAskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginAichatAskRequestWithDefaults() *PluginAichatAskRequest {
	this := PluginAichatAskRequest{}
	return &this
}

// GetQuery returns the Query field value
func (o *PluginAichatAskRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *PluginAichatAskRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *PluginAichatAskRequest) SetQuery(v string) {
	o.Query = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *PluginAichatAskRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginAichatAskRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *PluginAichatAskRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *PluginAichatAskRequest) SetModel(v string) {
	o.Model = &v
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *PluginAichatAskRequest) GetLang() string {
	if o == nil || IsNil(o.Lang) {
		var ret string
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginAichatAskRequest) GetLangOk() (*string, bool) {
	if o == nil || IsNil(o.Lang) {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *PluginAichatAskRequest) HasLang() bool {
	if o != nil && !IsNil(o.Lang) {
		return true
	}

	return false
}

// SetLang gets a reference to the given string and assigns it to the Lang field.
func (o *PluginAichatAskRequest) SetLang(v string) {
	o.Lang = &v
}

func (o PluginAichatAskRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginAichatAskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Lang) {
		toSerialize["lang"] = o.Lang
	}
	return toSerialize, nil
}

func (o *PluginAichatAskRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginAichatAskRequest := _PluginAichatAskRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPluginAichatAskRequest)

	if err != nil {
		return err
	}

	*o = PluginAichatAskRequest(varPluginAichatAskRequest)

	return err
}

type NullablePluginAichatAskRequest struct {
	value *PluginAichatAskRequest
	isSet bool
}

func (v NullablePluginAichatAskRequest) Get() *PluginAichatAskRequest {
	return v.value
}

func (v *NullablePluginAichatAskRequest) Set(val *PluginAichatAskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginAichatAskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginAichatAskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginAichatAskRequest(val *PluginAichatAskRequest) *NullablePluginAichatAskRequest {
	return &NullablePluginAichatAskRequest{value: val, isSet: true}
}

func (v NullablePluginAichatAskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginAichatAskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


