/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DokuwikiDeleteUsersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DokuwikiDeleteUsersRequest{}

// DokuwikiDeleteUsersRequest struct for DokuwikiDeleteUsersRequest
type DokuwikiDeleteUsersRequest struct {
	// 
	Usernames string `json:"usernames"`
}

type _DokuwikiDeleteUsersRequest DokuwikiDeleteUsersRequest

// NewDokuwikiDeleteUsersRequest instantiates a new DokuwikiDeleteUsersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDokuwikiDeleteUsersRequest(usernames string) *DokuwikiDeleteUsersRequest {
	this := DokuwikiDeleteUsersRequest{}
	this.Usernames = usernames
	return &this
}

// NewDokuwikiDeleteUsersRequestWithDefaults instantiates a new DokuwikiDeleteUsersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDokuwikiDeleteUsersRequestWithDefaults() *DokuwikiDeleteUsersRequest {
	this := DokuwikiDeleteUsersRequest{}
	return &this
}

// GetUsernames returns the Usernames field value
func (o *DokuwikiDeleteUsersRequest) GetUsernames() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Usernames
}

// GetUsernamesOk returns a tuple with the Usernames field value
// and a boolean to check if the value has been set.
func (o *DokuwikiDeleteUsersRequest) GetUsernamesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usernames, true
}

// SetUsernames sets field value
func (o *DokuwikiDeleteUsersRequest) SetUsernames(v string) {
	o.Usernames = v
}

func (o DokuwikiDeleteUsersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DokuwikiDeleteUsersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["usernames"] = o.Usernames
	return toSerialize, nil
}

func (o *DokuwikiDeleteUsersRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"usernames",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDokuwikiDeleteUsersRequest := _DokuwikiDeleteUsersRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDokuwikiDeleteUsersRequest)

	if err != nil {
		return err
	}

	*o = DokuwikiDeleteUsersRequest(varDokuwikiDeleteUsersRequest)

	return err
}

type NullableDokuwikiDeleteUsersRequest struct {
	value *DokuwikiDeleteUsersRequest
	isSet bool
}

func (v NullableDokuwikiDeleteUsersRequest) Get() *DokuwikiDeleteUsersRequest {
	return v.value
}

func (v *NullableDokuwikiDeleteUsersRequest) Set(val *DokuwikiDeleteUsersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDokuwikiDeleteUsersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDokuwikiDeleteUsersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDokuwikiDeleteUsersRequest(val *DokuwikiDeleteUsersRequest) *NullableDokuwikiDeleteUsersRequest {
	return &NullableDokuwikiDeleteUsersRequest{value: val, isSet: true}
}

func (v NullableDokuwikiDeleteUsersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDokuwikiDeleteUsersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


