/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
)

// checks if the CoreGetPageLinks200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreGetPageLinks200Response{}

// CoreGetPageLinks200Response struct for CoreGetPageLinks200Response
type CoreGetPageLinks200Response struct {
	// A list of links found on the given page
	Result []CoreGetPageLinks200ResponseResultInner `json:"result,omitempty"`
	Error *CoreGetAPIVersion200ResponseError `json:"error,omitempty"`
}

// NewCoreGetPageLinks200Response instantiates a new CoreGetPageLinks200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreGetPageLinks200Response() *CoreGetPageLinks200Response {
	this := CoreGetPageLinks200Response{}
	return &this
}

// NewCoreGetPageLinks200ResponseWithDefaults instantiates a new CoreGetPageLinks200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreGetPageLinks200ResponseWithDefaults() *CoreGetPageLinks200Response {
	this := CoreGetPageLinks200Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CoreGetPageLinks200Response) GetResult() []CoreGetPageLinks200ResponseResultInner {
	if o == nil || IsNil(o.Result) {
		var ret []CoreGetPageLinks200ResponseResultInner
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreGetPageLinks200Response) GetResultOk() ([]CoreGetPageLinks200ResponseResultInner, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CoreGetPageLinks200Response) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []CoreGetPageLinks200ResponseResultInner and assigns it to the Result field.
func (o *CoreGetPageLinks200Response) SetResult(v []CoreGetPageLinks200ResponseResultInner) {
	o.Result = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CoreGetPageLinks200Response) GetError() CoreGetAPIVersion200ResponseError {
	if o == nil || IsNil(o.Error) {
		var ret CoreGetAPIVersion200ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreGetPageLinks200Response) GetErrorOk() (*CoreGetAPIVersion200ResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CoreGetPageLinks200Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given CoreGetAPIVersion200ResponseError and assigns it to the Error field.
func (o *CoreGetPageLinks200Response) SetError(v CoreGetAPIVersion200ResponseError) {
	o.Error = &v
}

func (o CoreGetPageLinks200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreGetPageLinks200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableCoreGetPageLinks200Response struct {
	value *CoreGetPageLinks200Response
	isSet bool
}

func (v NullableCoreGetPageLinks200Response) Get() *CoreGetPageLinks200Response {
	return v.value
}

func (v *NullableCoreGetPageLinks200Response) Set(val *CoreGetPageLinks200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreGetPageLinks200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreGetPageLinks200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreGetPageLinks200Response(val *CoreGetPageLinks200Response) *NullableCoreGetPageLinks200Response {
	return &NullableCoreGetPageLinks200Response{value: val, isSet: true}
}

func (v NullableCoreGetPageLinks200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreGetPageLinks200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


