/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DokuwikiAppendPageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DokuwikiAppendPageRequest{}

// DokuwikiAppendPageRequest struct for DokuwikiAppendPageRequest
type DokuwikiAppendPageRequest struct {
	// 
	Id string `json:"id"`
	// 
	Text string `json:"text"`
	//  [_default: `[]`_]
	Params *string `json:"params,omitempty"`
}

type _DokuwikiAppendPageRequest DokuwikiAppendPageRequest

// NewDokuwikiAppendPageRequest instantiates a new DokuwikiAppendPageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDokuwikiAppendPageRequest(id string, text string) *DokuwikiAppendPageRequest {
	this := DokuwikiAppendPageRequest{}
	this.Id = id
	this.Text = text
	return &this
}

// NewDokuwikiAppendPageRequestWithDefaults instantiates a new DokuwikiAppendPageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDokuwikiAppendPageRequestWithDefaults() *DokuwikiAppendPageRequest {
	this := DokuwikiAppendPageRequest{}
	return &this
}

// GetId returns the Id field value
func (o *DokuwikiAppendPageRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DokuwikiAppendPageRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DokuwikiAppendPageRequest) SetId(v string) {
	o.Id = v
}

// GetText returns the Text field value
func (o *DokuwikiAppendPageRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *DokuwikiAppendPageRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *DokuwikiAppendPageRequest) SetText(v string) {
	o.Text = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *DokuwikiAppendPageRequest) GetParams() string {
	if o == nil || IsNil(o.Params) {
		var ret string
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DokuwikiAppendPageRequest) GetParamsOk() (*string, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *DokuwikiAppendPageRequest) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given string and assigns it to the Params field.
func (o *DokuwikiAppendPageRequest) SetParams(v string) {
	o.Params = &v
}

func (o DokuwikiAppendPageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DokuwikiAppendPageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["text"] = o.Text
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

func (o *DokuwikiAppendPageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDokuwikiAppendPageRequest := _DokuwikiAppendPageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDokuwikiAppendPageRequest)

	if err != nil {
		return err
	}

	*o = DokuwikiAppendPageRequest(varDokuwikiAppendPageRequest)

	return err
}

type NullableDokuwikiAppendPageRequest struct {
	value *DokuwikiAppendPageRequest
	isSet bool
}

func (v NullableDokuwikiAppendPageRequest) Get() *DokuwikiAppendPageRequest {
	return v.value
}

func (v *NullableDokuwikiAppendPageRequest) Set(val *DokuwikiAppendPageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDokuwikiAppendPageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDokuwikiAppendPageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDokuwikiAppendPageRequest(val *DokuwikiAppendPageRequest) *NullableDokuwikiAppendPageRequest {
	return &NullableDokuwikiAppendPageRequest{value: val, isSet: true}
}

func (v NullableDokuwikiAppendPageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDokuwikiAppendPageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


