/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WikiPutAttachmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WikiPutAttachmentRequest{}

// WikiPutAttachmentRequest struct for WikiPutAttachmentRequest
type WikiPutAttachmentRequest struct {
	// 
	Id string `json:"id"`
	// 
	File string `json:"file"`
	//  [_default: `[]`_]
	Params *string `json:"params,omitempty"`
}

type _WikiPutAttachmentRequest WikiPutAttachmentRequest

// NewWikiPutAttachmentRequest instantiates a new WikiPutAttachmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWikiPutAttachmentRequest(id string, file string) *WikiPutAttachmentRequest {
	this := WikiPutAttachmentRequest{}
	this.Id = id
	this.File = file
	return &this
}

// NewWikiPutAttachmentRequestWithDefaults instantiates a new WikiPutAttachmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWikiPutAttachmentRequestWithDefaults() *WikiPutAttachmentRequest {
	this := WikiPutAttachmentRequest{}
	return &this
}

// GetId returns the Id field value
func (o *WikiPutAttachmentRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WikiPutAttachmentRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WikiPutAttachmentRequest) SetId(v string) {
	o.Id = v
}

// GetFile returns the File field value
func (o *WikiPutAttachmentRequest) GetFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *WikiPutAttachmentRequest) GetFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *WikiPutAttachmentRequest) SetFile(v string) {
	o.File = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *WikiPutAttachmentRequest) GetParams() string {
	if o == nil || IsNil(o.Params) {
		var ret string
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WikiPutAttachmentRequest) GetParamsOk() (*string, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *WikiPutAttachmentRequest) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given string and assigns it to the Params field.
func (o *WikiPutAttachmentRequest) SetParams(v string) {
	o.Params = &v
}

func (o WikiPutAttachmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WikiPutAttachmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["file"] = o.File
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

func (o *WikiPutAttachmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWikiPutAttachmentRequest := _WikiPutAttachmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWikiPutAttachmentRequest)

	if err != nil {
		return err
	}

	*o = WikiPutAttachmentRequest(varWikiPutAttachmentRequest)

	return err
}

type NullableWikiPutAttachmentRequest struct {
	value *WikiPutAttachmentRequest
	isSet bool
}

func (v NullableWikiPutAttachmentRequest) Get() *WikiPutAttachmentRequest {
	return v.value
}

func (v *NullableWikiPutAttachmentRequest) Set(val *WikiPutAttachmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWikiPutAttachmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWikiPutAttachmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWikiPutAttachmentRequest(val *WikiPutAttachmentRequest) *NullableWikiPutAttachmentRequest {
	return &NullableWikiPutAttachmentRequest{value: val, isSet: true}
}

func (v NullableWikiPutAttachmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWikiPutAttachmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


