/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DokuwikiGetPagelistRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DokuwikiGetPagelistRequest{}

// DokuwikiGetPagelistRequest struct for DokuwikiGetPagelistRequest
type DokuwikiGetPagelistRequest struct {
	// 
	Ns string `json:"ns"`
	//  [_default: `[]`_]
	Opts *string `json:"opts,omitempty"`
}

type _DokuwikiGetPagelistRequest DokuwikiGetPagelistRequest

// NewDokuwikiGetPagelistRequest instantiates a new DokuwikiGetPagelistRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDokuwikiGetPagelistRequest(ns string) *DokuwikiGetPagelistRequest {
	this := DokuwikiGetPagelistRequest{}
	this.Ns = ns
	return &this
}

// NewDokuwikiGetPagelistRequestWithDefaults instantiates a new DokuwikiGetPagelistRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDokuwikiGetPagelistRequestWithDefaults() *DokuwikiGetPagelistRequest {
	this := DokuwikiGetPagelistRequest{}
	return &this
}

// GetNs returns the Ns field value
func (o *DokuwikiGetPagelistRequest) GetNs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ns
}

// GetNsOk returns a tuple with the Ns field value
// and a boolean to check if the value has been set.
func (o *DokuwikiGetPagelistRequest) GetNsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ns, true
}

// SetNs sets field value
func (o *DokuwikiGetPagelistRequest) SetNs(v string) {
	o.Ns = v
}

// GetOpts returns the Opts field value if set, zero value otherwise.
func (o *DokuwikiGetPagelistRequest) GetOpts() string {
	if o == nil || IsNil(o.Opts) {
		var ret string
		return ret
	}
	return *o.Opts
}

// GetOptsOk returns a tuple with the Opts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DokuwikiGetPagelistRequest) GetOptsOk() (*string, bool) {
	if o == nil || IsNil(o.Opts) {
		return nil, false
	}
	return o.Opts, true
}

// HasOpts returns a boolean if a field has been set.
func (o *DokuwikiGetPagelistRequest) HasOpts() bool {
	if o != nil && !IsNil(o.Opts) {
		return true
	}

	return false
}

// SetOpts gets a reference to the given string and assigns it to the Opts field.
func (o *DokuwikiGetPagelistRequest) SetOpts(v string) {
	o.Opts = &v
}

func (o DokuwikiGetPagelistRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DokuwikiGetPagelistRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ns"] = o.Ns
	if !IsNil(o.Opts) {
		toSerialize["opts"] = o.Opts
	}
	return toSerialize, nil
}

func (o *DokuwikiGetPagelistRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ns",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDokuwikiGetPagelistRequest := _DokuwikiGetPagelistRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDokuwikiGetPagelistRequest)

	if err != nil {
		return err
	}

	*o = DokuwikiGetPagelistRequest(varDokuwikiGetPagelistRequest)

	return err
}

type NullableDokuwikiGetPagelistRequest struct {
	value *DokuwikiGetPagelistRequest
	isSet bool
}

func (v NullableDokuwikiGetPagelistRequest) Get() *DokuwikiGetPagelistRequest {
	return v.value
}

func (v *NullableDokuwikiGetPagelistRequest) Set(val *DokuwikiGetPagelistRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDokuwikiGetPagelistRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDokuwikiGetPagelistRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDokuwikiGetPagelistRequest(val *DokuwikiGetPagelistRequest) *NullableDokuwikiGetPagelistRequest {
	return &NullableDokuwikiGetPagelistRequest{value: val, isSet: true}
}

func (v NullableDokuwikiGetPagelistRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDokuwikiGetPagelistRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


