/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoreSavePageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreSavePageRequest{}

// CoreSavePageRequest struct for CoreSavePageRequest
type CoreSavePageRequest struct {
	// page id
	Page string `json:"page"`
	// wiki text
	Text string `json:"text"`
	// edit summary [_default: `\"\"`_]
	Summary *string `json:"summary,omitempty"`
	// whether this is a minor edit [_default: `false`_]
	Isminor *bool `json:"isminor,omitempty"`
}

type _CoreSavePageRequest CoreSavePageRequest

// NewCoreSavePageRequest instantiates a new CoreSavePageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreSavePageRequest(page string, text string) *CoreSavePageRequest {
	this := CoreSavePageRequest{}
	this.Page = page
	this.Text = text
	return &this
}

// NewCoreSavePageRequestWithDefaults instantiates a new CoreSavePageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreSavePageRequestWithDefaults() *CoreSavePageRequest {
	this := CoreSavePageRequest{}
	return &this
}

// GetPage returns the Page field value
func (o *CoreSavePageRequest) GetPage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *CoreSavePageRequest) GetPageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *CoreSavePageRequest) SetPage(v string) {
	o.Page = v
}

// GetText returns the Text field value
func (o *CoreSavePageRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *CoreSavePageRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *CoreSavePageRequest) SetText(v string) {
	o.Text = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *CoreSavePageRequest) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreSavePageRequest) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *CoreSavePageRequest) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *CoreSavePageRequest) SetSummary(v string) {
	o.Summary = &v
}

// GetIsminor returns the Isminor field value if set, zero value otherwise.
func (o *CoreSavePageRequest) GetIsminor() bool {
	if o == nil || IsNil(o.Isminor) {
		var ret bool
		return ret
	}
	return *o.Isminor
}

// GetIsminorOk returns a tuple with the Isminor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreSavePageRequest) GetIsminorOk() (*bool, bool) {
	if o == nil || IsNil(o.Isminor) {
		return nil, false
	}
	return o.Isminor, true
}

// HasIsminor returns a boolean if a field has been set.
func (o *CoreSavePageRequest) HasIsminor() bool {
	if o != nil && !IsNil(o.Isminor) {
		return true
	}

	return false
}

// SetIsminor gets a reference to the given bool and assigns it to the Isminor field.
func (o *CoreSavePageRequest) SetIsminor(v bool) {
	o.Isminor = &v
}

func (o CoreSavePageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreSavePageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	toSerialize["text"] = o.Text
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Isminor) {
		toSerialize["isminor"] = o.Isminor
	}
	return toSerialize, nil
}

func (o *CoreSavePageRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoreSavePageRequest := _CoreSavePageRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoreSavePageRequest)

	if err != nil {
		return err
	}

	*o = CoreSavePageRequest(varCoreSavePageRequest)

	return err
}

type NullableCoreSavePageRequest struct {
	value *CoreSavePageRequest
	isSet bool
}

func (v NullableCoreSavePageRequest) Get() *CoreSavePageRequest {
	return v.value
}

func (v *NullableCoreSavePageRequest) Set(val *CoreSavePageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreSavePageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreSavePageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreSavePageRequest(val *CoreSavePageRequest) *NullableCoreSavePageRequest {
	return &NullableCoreSavePageRequest{value: val, isSet: true}
}

func (v NullableCoreSavePageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreSavePageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


