/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoreGetPageHistoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreGetPageHistoryRequest{}

// CoreGetPageHistoryRequest struct for CoreGetPageHistoryRequest
type CoreGetPageHistoryRequest struct {
	// page id
	Page string `json:"page"`
	// skip the first n changelog lines, 0 starts at the current revision [_default: `0`_]
	First *int32 `json:"first,omitempty"`
}

type _CoreGetPageHistoryRequest CoreGetPageHistoryRequest

// NewCoreGetPageHistoryRequest instantiates a new CoreGetPageHistoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreGetPageHistoryRequest(page string) *CoreGetPageHistoryRequest {
	this := CoreGetPageHistoryRequest{}
	this.Page = page
	return &this
}

// NewCoreGetPageHistoryRequestWithDefaults instantiates a new CoreGetPageHistoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreGetPageHistoryRequestWithDefaults() *CoreGetPageHistoryRequest {
	this := CoreGetPageHistoryRequest{}
	return &this
}

// GetPage returns the Page field value
func (o *CoreGetPageHistoryRequest) GetPage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *CoreGetPageHistoryRequest) GetPageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *CoreGetPageHistoryRequest) SetPage(v string) {
	o.Page = v
}

// GetFirst returns the First field value if set, zero value otherwise.
func (o *CoreGetPageHistoryRequest) GetFirst() int32 {
	if o == nil || IsNil(o.First) {
		var ret int32
		return ret
	}
	return *o.First
}

// GetFirstOk returns a tuple with the First field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreGetPageHistoryRequest) GetFirstOk() (*int32, bool) {
	if o == nil || IsNil(o.First) {
		return nil, false
	}
	return o.First, true
}

// HasFirst returns a boolean if a field has been set.
func (o *CoreGetPageHistoryRequest) HasFirst() bool {
	if o != nil && !IsNil(o.First) {
		return true
	}

	return false
}

// SetFirst gets a reference to the given int32 and assigns it to the First field.
func (o *CoreGetPageHistoryRequest) SetFirst(v int32) {
	o.First = &v
}

func (o CoreGetPageHistoryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreGetPageHistoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	if !IsNil(o.First) {
		toSerialize["first"] = o.First
	}
	return toSerialize, nil
}

func (o *CoreGetPageHistoryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoreGetPageHistoryRequest := _CoreGetPageHistoryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoreGetPageHistoryRequest)

	if err != nil {
		return err
	}

	*o = CoreGetPageHistoryRequest(varCoreGetPageHistoryRequest)

	return err
}

type NullableCoreGetPageHistoryRequest struct {
	value *CoreGetPageHistoryRequest
	isSet bool
}

func (v NullableCoreGetPageHistoryRequest) Get() *CoreGetPageHistoryRequest {
	return v.value
}

func (v *NullableCoreGetPageHistoryRequest) Set(val *CoreGetPageHistoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreGetPageHistoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreGetPageHistoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreGetPageHistoryRequest(val *CoreGetPageHistoryRequest) *NullableCoreGetPageHistoryRequest {
	return &NullableCoreGetPageHistoryRequest{value: val, isSet: true}
}

func (v NullableCoreGetPageHistoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreGetPageHistoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


