/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PluginUsermanagerDeleteUserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginUsermanagerDeleteUserRequest{}

// PluginUsermanagerDeleteUserRequest struct for PluginUsermanagerDeleteUserRequest
type PluginUsermanagerDeleteUserRequest struct {
	// The login name of the user to delete
	User []string `json:"user"`
}

type _PluginUsermanagerDeleteUserRequest PluginUsermanagerDeleteUserRequest

// NewPluginUsermanagerDeleteUserRequest instantiates a new PluginUsermanagerDeleteUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginUsermanagerDeleteUserRequest(user []string) *PluginUsermanagerDeleteUserRequest {
	this := PluginUsermanagerDeleteUserRequest{}
	this.User = user
	return &this
}

// NewPluginUsermanagerDeleteUserRequestWithDefaults instantiates a new PluginUsermanagerDeleteUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginUsermanagerDeleteUserRequestWithDefaults() *PluginUsermanagerDeleteUserRequest {
	this := PluginUsermanagerDeleteUserRequest{}
	return &this
}

// GetUser returns the User field value
func (o *PluginUsermanagerDeleteUserRequest) GetUser() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *PluginUsermanagerDeleteUserRequest) GetUserOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.User, true
}

// SetUser sets field value
func (o *PluginUsermanagerDeleteUserRequest) SetUser(v []string) {
	o.User = v
}

func (o PluginUsermanagerDeleteUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginUsermanagerDeleteUserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User
	return toSerialize, nil
}

func (o *PluginUsermanagerDeleteUserRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginUsermanagerDeleteUserRequest := _PluginUsermanagerDeleteUserRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPluginUsermanagerDeleteUserRequest)

	if err != nil {
		return err
	}

	*o = PluginUsermanagerDeleteUserRequest(varPluginUsermanagerDeleteUserRequest)

	return err
}

type NullablePluginUsermanagerDeleteUserRequest struct {
	value *PluginUsermanagerDeleteUserRequest
	isSet bool
}

func (v NullablePluginUsermanagerDeleteUserRequest) Get() *PluginUsermanagerDeleteUserRequest {
	return v.value
}

func (v *NullablePluginUsermanagerDeleteUserRequest) Set(val *PluginUsermanagerDeleteUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginUsermanagerDeleteUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginUsermanagerDeleteUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginUsermanagerDeleteUserRequest(val *PluginUsermanagerDeleteUserRequest) *NullablePluginUsermanagerDeleteUserRequest {
	return &NullablePluginUsermanagerDeleteUserRequest{value: val, isSet: true}
}

func (v NullablePluginUsermanagerDeleteUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginUsermanagerDeleteUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


