/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
)

// checks if the CoreListPages200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreListPages200Response{}

// CoreListPages200Response struct for CoreListPages200Response
type CoreListPages200Response struct {
	// A list of matching pages
	Result []CoreListPages200ResponseResultInner `json:"result,omitempty"`
	Error *CoreGetAPIVersion200ResponseError `json:"error,omitempty"`
}

// NewCoreListPages200Response instantiates a new CoreListPages200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreListPages200Response() *CoreListPages200Response {
	this := CoreListPages200Response{}
	return &this
}

// NewCoreListPages200ResponseWithDefaults instantiates a new CoreListPages200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreListPages200ResponseWithDefaults() *CoreListPages200Response {
	this := CoreListPages200Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CoreListPages200Response) GetResult() []CoreListPages200ResponseResultInner {
	if o == nil || IsNil(o.Result) {
		var ret []CoreListPages200ResponseResultInner
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreListPages200Response) GetResultOk() ([]CoreListPages200ResponseResultInner, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CoreListPages200Response) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []CoreListPages200ResponseResultInner and assigns it to the Result field.
func (o *CoreListPages200Response) SetResult(v []CoreListPages200ResponseResultInner) {
	o.Result = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CoreListPages200Response) GetError() CoreGetAPIVersion200ResponseError {
	if o == nil || IsNil(o.Error) {
		var ret CoreGetAPIVersion200ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreListPages200Response) GetErrorOk() (*CoreGetAPIVersion200ResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CoreListPages200Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given CoreGetAPIVersion200ResponseError and assigns it to the Error field.
func (o *CoreListPages200Response) SetError(v CoreGetAPIVersion200ResponseError) {
	o.Error = &v
}

func (o CoreListPages200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreListPages200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableCoreListPages200Response struct {
	value *CoreListPages200Response
	isSet bool
}

func (v NullableCoreListPages200Response) Get() *CoreListPages200Response {
	return v.value
}

func (v *NullableCoreListPages200Response) Set(val *CoreListPages200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreListPages200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreListPages200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreListPages200Response(val *CoreListPages200Response) *NullableCoreListPages200Response {
	return &NullableCoreListPages200Response{value: val, isSet: true}
}

func (v NullableCoreListPages200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreListPages200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


