/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CoreSearchPagesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreSearchPagesRequest{}

// CoreSearchPagesRequest struct for CoreSearchPagesRequest
type CoreSearchPagesRequest struct {
	// The search query as supported by the DokuWiki search
	Query string `json:"query"`
}

type _CoreSearchPagesRequest CoreSearchPagesRequest

// NewCoreSearchPagesRequest instantiates a new CoreSearchPagesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreSearchPagesRequest(query string) *CoreSearchPagesRequest {
	this := CoreSearchPagesRequest{}
	this.Query = query
	return &this
}

// NewCoreSearchPagesRequestWithDefaults instantiates a new CoreSearchPagesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreSearchPagesRequestWithDefaults() *CoreSearchPagesRequest {
	this := CoreSearchPagesRequest{}
	return &this
}

// GetQuery returns the Query field value
func (o *CoreSearchPagesRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *CoreSearchPagesRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *CoreSearchPagesRequest) SetQuery(v string) {
	o.Query = v
}

func (o CoreSearchPagesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreSearchPagesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	return toSerialize, nil
}

func (o *CoreSearchPagesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCoreSearchPagesRequest := _CoreSearchPagesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCoreSearchPagesRequest)

	if err != nil {
		return err
	}

	*o = CoreSearchPagesRequest(varCoreSearchPagesRequest)

	return err
}

type NullableCoreSearchPagesRequest struct {
	value *CoreSearchPagesRequest
	isSet bool
}

func (v NullableCoreSearchPagesRequest) Get() *CoreSearchPagesRequest {
	return v.value
}

func (v *NullableCoreSearchPagesRequest) Set(val *CoreSearchPagesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreSearchPagesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreSearchPagesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreSearchPagesRequest(val *CoreSearchPagesRequest) *NullableCoreSearchPagesRequest {
	return &NullableCoreSearchPagesRequest{value: val, isSet: true}
}

func (v NullableCoreSearchPagesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreSearchPagesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


