/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PluginMoveRenameMediaRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginMoveRenameMediaRequest{}

// PluginMoveRenameMediaRequest struct for PluginMoveRenameMediaRequest
type PluginMoveRenameMediaRequest struct {
	// The original media ID
	FromId string `json:"fromId"`
	// The new media ID
	ToId string `json:"toId"`
}

type _PluginMoveRenameMediaRequest PluginMoveRenameMediaRequest

// NewPluginMoveRenameMediaRequest instantiates a new PluginMoveRenameMediaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginMoveRenameMediaRequest(fromId string, toId string) *PluginMoveRenameMediaRequest {
	this := PluginMoveRenameMediaRequest{}
	this.FromId = fromId
	this.ToId = toId
	return &this
}

// NewPluginMoveRenameMediaRequestWithDefaults instantiates a new PluginMoveRenameMediaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginMoveRenameMediaRequestWithDefaults() *PluginMoveRenameMediaRequest {
	this := PluginMoveRenameMediaRequest{}
	return &this
}

// GetFromId returns the FromId field value
func (o *PluginMoveRenameMediaRequest) GetFromId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromId
}

// GetFromIdOk returns a tuple with the FromId field value
// and a boolean to check if the value has been set.
func (o *PluginMoveRenameMediaRequest) GetFromIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromId, true
}

// SetFromId sets field value
func (o *PluginMoveRenameMediaRequest) SetFromId(v string) {
	o.FromId = v
}

// GetToId returns the ToId field value
func (o *PluginMoveRenameMediaRequest) GetToId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToId
}

// GetToIdOk returns a tuple with the ToId field value
// and a boolean to check if the value has been set.
func (o *PluginMoveRenameMediaRequest) GetToIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToId, true
}

// SetToId sets field value
func (o *PluginMoveRenameMediaRequest) SetToId(v string) {
	o.ToId = v
}

func (o PluginMoveRenameMediaRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginMoveRenameMediaRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fromId"] = o.FromId
	toSerialize["toId"] = o.ToId
	return toSerialize, nil
}

func (o *PluginMoveRenameMediaRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fromId",
		"toId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginMoveRenameMediaRequest := _PluginMoveRenameMediaRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPluginMoveRenameMediaRequest)

	if err != nil {
		return err
	}

	*o = PluginMoveRenameMediaRequest(varPluginMoveRenameMediaRequest)

	return err
}

type NullablePluginMoveRenameMediaRequest struct {
	value *PluginMoveRenameMediaRequest
	isSet bool
}

func (v NullablePluginMoveRenameMediaRequest) Get() *PluginMoveRenameMediaRequest {
	return v.value
}

func (v *NullablePluginMoveRenameMediaRequest) Set(val *PluginMoveRenameMediaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginMoveRenameMediaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginMoveRenameMediaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginMoveRenameMediaRequest(val *PluginMoveRenameMediaRequest) *NullablePluginMoveRenameMediaRequest {
	return &NullablePluginMoveRenameMediaRequest{value: val, isSet: true}
}

func (v NullablePluginMoveRenameMediaRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginMoveRenameMediaRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


