/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PluginExtensionSearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginExtensionSearchRequest{}

// PluginExtensionSearchRequest struct for PluginExtensionSearchRequest
type PluginExtensionSearchRequest struct {
	// The keyword(s) to search for
	Query string `json:"query"`
	// Maximum number of results (default 10) [_default: `10`_]
	Max *int32 `json:"max,omitempty"`
}

type _PluginExtensionSearchRequest PluginExtensionSearchRequest

// NewPluginExtensionSearchRequest instantiates a new PluginExtensionSearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginExtensionSearchRequest(query string) *PluginExtensionSearchRequest {
	this := PluginExtensionSearchRequest{}
	this.Query = query
	return &this
}

// NewPluginExtensionSearchRequestWithDefaults instantiates a new PluginExtensionSearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginExtensionSearchRequestWithDefaults() *PluginExtensionSearchRequest {
	this := PluginExtensionSearchRequest{}
	return &this
}

// GetQuery returns the Query field value
func (o *PluginExtensionSearchRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *PluginExtensionSearchRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *PluginExtensionSearchRequest) SetQuery(v string) {
	o.Query = v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *PluginExtensionSearchRequest) GetMax() int32 {
	if o == nil || IsNil(o.Max) {
		var ret int32
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PluginExtensionSearchRequest) GetMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *PluginExtensionSearchRequest) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given int32 and assigns it to the Max field.
func (o *PluginExtensionSearchRequest) SetMax(v int32) {
	o.Max = &v
}

func (o PluginExtensionSearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginExtensionSearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	return toSerialize, nil
}

func (o *PluginExtensionSearchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginExtensionSearchRequest := _PluginExtensionSearchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPluginExtensionSearchRequest)

	if err != nil {
		return err
	}

	*o = PluginExtensionSearchRequest(varPluginExtensionSearchRequest)

	return err
}

type NullablePluginExtensionSearchRequest struct {
	value *PluginExtensionSearchRequest
	isSet bool
}

func (v NullablePluginExtensionSearchRequest) Get() *PluginExtensionSearchRequest {
	return v.value
}

func (v *NullablePluginExtensionSearchRequest) Set(val *PluginExtensionSearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginExtensionSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginExtensionSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginExtensionSearchRequest(val *PluginExtensionSearchRequest) *NullablePluginExtensionSearchRequest {
	return &NullablePluginExtensionSearchRequest{value: val, isSet: true}
}

func (v NullablePluginExtensionSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginExtensionSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


