/*
DokuWiki API

The DokuWiki API OpenAPI specification

API version: 14
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dokuwiki

import (
	"encoding/json"
)

// checks if the CoreAclCheck200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoreAclCheck200Response{}

// CoreAclCheck200Response struct for CoreAclCheck200Response
type CoreAclCheck200Response struct {
	// permission level
	Result *int32 `json:"result,omitempty"`
	Error *CoreGetAPIVersion200ResponseError `json:"error,omitempty"`
}

// NewCoreAclCheck200Response instantiates a new CoreAclCheck200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreAclCheck200Response() *CoreAclCheck200Response {
	this := CoreAclCheck200Response{}
	return &this
}

// NewCoreAclCheck200ResponseWithDefaults instantiates a new CoreAclCheck200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreAclCheck200ResponseWithDefaults() *CoreAclCheck200Response {
	this := CoreAclCheck200Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CoreAclCheck200Response) GetResult() int32 {
	if o == nil || IsNil(o.Result) {
		var ret int32
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreAclCheck200Response) GetResultOk() (*int32, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CoreAclCheck200Response) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given int32 and assigns it to the Result field.
func (o *CoreAclCheck200Response) SetResult(v int32) {
	o.Result = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CoreAclCheck200Response) GetError() CoreGetAPIVersion200ResponseError {
	if o == nil || IsNil(o.Error) {
		var ret CoreGetAPIVersion200ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreAclCheck200Response) GetErrorOk() (*CoreGetAPIVersion200ResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CoreAclCheck200Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given CoreGetAPIVersion200ResponseError and assigns it to the Error field.
func (o *CoreAclCheck200Response) SetError(v CoreGetAPIVersion200ResponseError) {
	o.Error = &v
}

func (o CoreAclCheck200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoreAclCheck200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableCoreAclCheck200Response struct {
	value *CoreAclCheck200Response
	isSet bool
}

func (v NullableCoreAclCheck200Response) Get() *CoreAclCheck200Response {
	return v.value
}

func (v *NullableCoreAclCheck200Response) Set(val *CoreAclCheck200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreAclCheck200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreAclCheck200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreAclCheck200Response(val *CoreAclCheck200Response) *NullableCoreAclCheck200Response {
	return &NullableCoreAclCheck200Response{value: val, isSet: true}
}

func (v NullableCoreAclCheck200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreAclCheck200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


