// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package coresearchpages

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SearchPagesPostResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Error object in case of an error
    error SearchPagesPostResponse_errorable
    // A list of matching pages
    result []SearchPagesPostResponse_resultable
}
// NewSearchPagesPostResponse instantiates a new SearchPagesPostResponse and sets the default values.
func NewSearchPagesPostResponse()(*SearchPagesPostResponse) {
    m := &SearchPagesPostResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateSearchPagesPostResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSearchPagesPostResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSearchPagesPostResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SearchPagesPostResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetError gets the error property value. Error object in case of an error
// returns a SearchPagesPostResponse_errorable when successful
func (m *SearchPagesPostResponse) GetError()(SearchPagesPostResponse_errorable) {
    return m.error
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SearchPagesPostResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["error"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSearchPagesPostResponse_errorFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetError(val.(SearchPagesPostResponse_errorable))
        }
        return nil
    }
    res["result"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateSearchPagesPostResponse_resultFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]SearchPagesPostResponse_resultable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(SearchPagesPostResponse_resultable)
                }
            }
            m.SetResult(res)
        }
        return nil
    }
    return res
}
// GetResult gets the result property value. A list of matching pages
// returns a []SearchPagesPostResponse_resultable when successful
func (m *SearchPagesPostResponse) GetResult()([]SearchPagesPostResponse_resultable) {
    return m.result
}
// Serialize serializes information the current object
func (m *SearchPagesPostResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("error", m.GetError())
        if err != nil {
            return err
        }
    }
    if m.GetResult() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetResult()))
        for i, v := range m.GetResult() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("result", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SearchPagesPostResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetError sets the error property value. Error object in case of an error
func (m *SearchPagesPostResponse) SetError(value SearchPagesPostResponse_errorable)() {
    m.error = value
}
// SetResult sets the result property value. A list of matching pages
func (m *SearchPagesPostResponse) SetResult(value []SearchPagesPostResponse_resultable)() {
    m.result = value
}
type SearchPagesPostResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetError()(SearchPagesPostResponse_errorable)
    GetResult()([]SearchPagesPostResponse_resultable)
    SetError(value SearchPagesPostResponse_errorable)()
    SetResult(value []SearchPagesPostResponse_resultable)()
}
